site_name: castiron
site_description: A schema→typed-code compiler for Python.
site_url: https://kmbhm1.github.io/castiron/
repo_url: https://github.com/kmbhm1/castiron
repo_name: kmbhm1/castiron
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
