"""The corpus case table: inputs, configs, goldens, and the defects each golden encodes.

This module is **declarative**. It states what the corpus contains; every assertion about it
lives in a ``test_*.py`` sibling, and every artifact it names is regenerated by
``tests.unit.corpus.regenerate``.

Why a golden is not automatically an endorsement
------------------------------------------------
A golden is a several-thousand-line assertion that *current output is correct*. Some of
castiron's current output is **known wrong** — five open WORKPLAN rows produce bytes that reach
a committed golden. Left implicit, this corpus would quietly cement those bugs as the contract,
and the day one is fixed the cheapest response to the red test would be "regenerate the golden",
silently re-endorsing whatever replaced it.

So every known-wrong region is **named**: :data:`KNOWN_DEFECTS` carries one entry per WORKPLAN
row whose output reaches a golden, ``test_witnesses.py`` asserts each defect's evidence **is
present**, and each :class:`CorpusCase` declares ``status='characterized'`` plus the row ids it
carries. ``status='asserted'`` means the stronger thing: *no known defect reaches these bytes.*

Typing note (spec §12, Hard Rule #6): :attr:`CorpusCase.emitter_config` holds a **real**
:class:`castiron.emitters.EmitterConfig` — never six loose booleans, never a parallel dataclass.
The config axis names are derived from ``dataclasses.fields(EmitterConfig)`` at runtime, so a new
toggle widens the sweep automatically instead of silently escaping it.
"""

import dataclasses
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from castiron.emitters import EmitterConfig

#: ``tests/unit/corpus/``.
CORPUS_DIR = Path(__file__).parent

#: ``tests/unit/corpus/inputs/`` — committed source documents. **Never** written by the tool.
INPUTS_DIR = CORPUS_DIR / 'inputs'

#: ``tests/unit/corpus/golden/`` — committed IR and emitted-module goldens.
GOLDEN_DIR = CORPUS_DIR / 'golden'

#: ``tests/unit/corpus/fingerprints/`` — committed per-config fingerprint manifests.
FINGERPRINT_DIR = CORPUS_DIR / 'fingerprints'

#: The repository root (``tests/unit/corpus`` → ``tests/unit`` → ``tests`` → root).
REPO_ROOT = CORPUS_DIR.parents[2]

#: CI-005's hand-authored document, **referenced and never copied** — four other test modules
#: already assert against it, and a second copy would be a second thing to keep in sync.
FIXTURE_INPUT = REPO_ROOT / 'tests' / 'unit' / 'sources' / 'openapi' / 'fixtures' / 'postgrest_openapi.json'

#: CI-005's committed golden module. ``openapi-fixture-default`` points at it rather than
#: committing a duplicate: it is already exactly ``PydanticEmitter(EmitterConfig()).emit(...)``.
FIXTURE_GOLDEN_MODULE = REPO_ROOT / 'tests' / 'unit' / 'sources' / 'openapi' / 'golden' / 'schema.py.txt'

#: The one :class:`EmitterConfig` field that does **not** affect output. It changes
#: :attr:`castiron.emitters.EmittedFile.path`, never ``.content`` — determinism axis A8 asserts
#: exactly that, which is what licenses excluding it from the sweep.
NON_OUTPUT_AFFECTING_FIELD = 'output_filename'

#: A *source* option that affects output but is not an :class:`EmitterConfig` field, so the sweep
#: is 7 axes rather than 6.
SOURCE_AXIS = 'infer_generated_primary_keys'

#: The command that rewrites every committed golden. Quoted in every failure message, because a
#: failure a reader cannot act on is a failure that gets worked around.
REGENERATE_COMMAND = 'uv run python -m tests.unit.corpus.regenerate'


def config_axes() -> tuple[str, ...]:
    """Return the output-affecting config axis names, sorted.

    Derived from :func:`dataclasses.fields` rather than a hand-maintained list, so adding a
    seventh :class:`EmitterConfig` toggle automatically widens the manifest sweep — and
    ``test_corpus_selfcheck.py`` fails until the manifests are regenerated to cover it. That is
    CI-072's "enumerate, do not sample" made structural instead of remembered.

    Returns:
        The 7 axis names in sorted order.
    """
    emitter_axes = {f.name for f in dataclasses.fields(EmitterConfig) if f.name != NON_OUTPUT_AFFECTING_FIELD}
    return tuple(sorted(emitter_axes | {SOURCE_AXIS}))


@dataclass(frozen=True)
class SourceOptions:
    """The output-affecting keyword options of :func:`build_schema_from_document`.

    ⚠ **Debt, recorded deliberately (spec §12).** This exists only because those keywords are
    not modelled anywhere in ``src/`` today. It holds **exactly** those two and must not grow
    into a general config object. When CI-010 introduces a real source-options type in ``src/``,
    this must be **replaced** by it, not kept alongside it — two shapes for one concept is the
    Hard Rule #6 violation this note exists to prevent.

    ``disable_model_prefix_protection`` appears here *and* on :class:`EmitterConfig` because the
    product genuinely takes it in both places: ``castiron.cli.gen`` passes one flag to
    ``build_schema_from_document`` and to ``EmitterConfig``. The corpus mirrors that wiring, and
    ``test_corpus_selfcheck.py`` asserts the two never disagree in a case.

    Attributes:
        infer_generated_primary_keys: Report a sole NOT NULL integer primary key as identity.
        disable_model_prefix_protection: Do not rename ``model_``-prefixed columns.
    """

    infer_generated_primary_keys: bool = False
    disable_model_prefix_protection: bool = False


@dataclass(frozen=True)
class Defect:
    """A known-wrong behaviour whose output reaches a committed golden.

    Attributes:
        row_id: The WORKPLAN row that owns the fix (e.g. ``'CI-075'``).
        summary: One line, in the row's own words.
        why_it_is_wrong: What correct output would look like instead. This is the field that
            makes the witness test's failure message actionable rather than merely loud.
    """

    row_id: str
    summary: str
    why_it_is_wrong: str


@dataclass(frozen=True)
class InputFamily:
    """One committed source document and its provenance record.

    Attributes:
        family_id: The stem shared by the case ids built from this input.
        input_path: The document on disk.
        provenance_path: The sibling ``*.provenance.json``, or ``None`` for the CI-005 fixture,
            which predates the corpus and lives under ``tests/unit/sources/openapi/``.
        schema: The schema the document describes (it never states its own name).
        origin: ``'captured'`` from a real PostgREST, or ``'synthetic'`` (hand-authored).
    """

    family_id: str
    input_path: Path
    provenance_path: Path | None
    schema: str
    origin: Literal['captured', 'synthetic']


@dataclass(frozen=True)
class CorpusCase:
    """One (input, config) point with committed goldens.

    Attributes:
        case_id: ``<input-family>-<config-name>``. One string, one meaning: the pytest
            parametrization id, the golden file stem, and the manifest header all use it.
        family: The input this case reads.
        source_options: What ``build_schema_from_document`` is called with.
        emitter_config: The **real** :class:`EmitterConfig` the emitter is constructed with.
        status: ``'asserted'`` ⇒ no known defect reaches these bytes. ``'characterized'`` ⇒ at
            least one does, and ``defects`` names every one.
        defects: WORKPLAN row ids, all keys of :data:`KNOWN_DEFECTS`.
        compiles: Whether the emitted module is expected to parse. Asserted **exactly**, so a
            ``False`` that becomes ``True`` goes red and names the row that must have been fixed.
        golden_module: The committed emitted module, or ``None`` for an IR-only case.
        golden_ir: The committed ``Schema.as_dict()`` golden.
    """

    case_id: str
    family: InputFamily
    source_options: SourceOptions
    emitter_config: EmitterConfig
    status: Literal['asserted', 'characterized']
    defects: tuple[str, ...]
    compiles: bool
    golden_module: Path | None
    golden_ir: Path

    @property
    def config_key(self) -> str:
        """The manifest row key for this case's config (see :func:`config_key`)."""
        return config_key(self.emitter_config, self.source_options)


def config_key(emitter_config: EmitterConfig, source_options: SourceOptions) -> str:
    """Render one point of the config space as a stable, total-ordered key.

    Full field names, never abbreviations: an abbreviation table is one more thing to rot, and
    the key is what a reviewer reads when a manifest row moves.

    Args:
        emitter_config: The emitter half of the config point.
        source_options: The source half.

    Returns:
        ``'add_null_parent_classes=0,disable_model_prefix_protection=0,...'``.
    """
    values: dict[str, bool] = {
        f.name: bool(getattr(emitter_config, f.name))
        for f in dataclasses.fields(EmitterConfig)
        if f.name != NON_OUTPUT_AFFECTING_FIELD
    }
    values[SOURCE_AXIS] = source_options.infer_generated_primary_keys
    return ','.join(f'{axis}={int(values[axis])}' for axis in config_axes())


def all_config_points() -> tuple[tuple[EmitterConfig, SourceOptions], ...]:
    """Return **every** reachable config point, ordered by :func:`config_key`.

    All 2**7 of them, not a sample. The measurement that forces this: 128 configs produce **96**
    distinct outputs on the ``testbed-public`` capture, so the axes *interact* — a corpus of
    single-flag-flip goldens provably cannot see an interaction, and a default-only corpus guards
    1 of 96 reachable outputs while ``check`` users run the other 95.

    Returns:
        128 ``(emitter_config, source_options)`` pairs in config-key order.
    """
    axes = config_axes()
    points: list[tuple[EmitterConfig, SourceOptions]] = []
    for bits in range(2 ** len(axes)):
        values = {axis: bool(bits >> index & 1) for index, axis in enumerate(axes)}
        source_options = SourceOptions(
            infer_generated_primary_keys=values[SOURCE_AXIS],
            # The CLI passes one flag to both halves; the corpus mirrors that wiring exactly.
            disable_model_prefix_protection=values['disable_model_prefix_protection'],
        )
        emitter_config = EmitterConfig(**{axis: values[axis] for axis in axes if axis != SOURCE_AXIS})
        points.append((emitter_config, source_options))
    return tuple(sorted(points, key=lambda point: config_key(*point)))


# ---------------------------------------------------------------------------
# Known defects — every WORKPLAN row whose output reaches a committed golden.
# ---------------------------------------------------------------------------

#: One entry per known-wrong behaviour visible in this corpus. Bookkeeping closes in **both**
#: directions (``test_corpus_selfcheck.py``): every id a case cites exists here, and every entry
#: here is cited by ≥1 case **and** witnessed by ≥1 test. A stale entry cannot survive.
KNOWN_DEFECTS: dict[str, Defect] = {
    'CI-075': Defect(
        row_id='CI-075',
        summary='classify_table_type() misreads an auto-updatable view as a BASE TABLE.',
        why_it_is_wrong=(
            'Path verbs follow Postgres auto-updatability, not write privileges, so three of the '
            "testbed's views are writable through the API and classify as BASE TABLE. They then "
            "keep a primary key they should not have: CI5-D14a downgrades a view's <pk/> marker to "
            'UNIQUE, and that downgrade never fires. Correct output has no "# Primary Keys" block '
            'on ActiveCustomers, LedgerSummary or WritableCustomerView -- exactly as OrderReport '
            'and MvCustomerSpend, the two views that DO classify correctly, already show.'
        ),
    ),
    'CI-076': Defect(
        row_id='CI-076',
        summary='The CI-005 fixture contains a shape PostgREST cannot emit: a VIEW as an FK target.',
        why_it_is_wrong=(
            "restricted_table.owner_id carries <fk table='active_users_view' column='id'/>. SEED-F1 "
            'CONFIRMED against PostgREST v14.14 and v12.2.3 that even when the base table is '
            'privilege-filtered and a view over it is visible, the marker names the invisible BASE '
            'TABLE, never the view. SQL cannot express it either -- a Postgres foreign key can only '
            'reference a table. The fixture is therefore synthetic, and this corpus never cites it '
            'as evidence about PostgREST.'
        ),
    ),
    'CI-084': Defect(
        row_id='CI-084',
        summary='A dangling FK marker yields is_foreign_key=True with an empty foreign_keys list.',
        why_it_is_wrong=(
            'PostgREST emits an <fk .../> marker naming a table absent from definitions (the role '
            'cannot see it), so ledger_refs.ledger_id is flagged a foreign key with nothing to '
            'point at -- a consumer reads is_foreign_key and then finds no relationship, which is '
            'the worst of the available behaviours. The right one (drop the flag / mark it dangling '
            '/ warn) is an open captain call, which is WHY this is characterized rather than fixed.'
        ),
    ),
    'CI-085': Defect(
        row_id='CI-085',
        summary='Column identifiers reach the emitter verbatim, so castiron emits unparseable Python.',
        why_it_is_wrong=(
            'Any quoted Postgres identifier is legal -- "2fast", "space name", "kebab-case" -- and '
            'PostgREST carries it verbatim, so it lands as a field name and the module will not '
            'parse. Distinct from CI-080 (measured): that is the enum MEMBER name, this is a COLUMN '
            'name; two call sites, two defects, one symptom. Correct output sanitizes the '
            'identifier and preserves the wire name via a Field(alias=...), as the reserved-word '
            'aliasing path already does.'
        ),
    ),
    'CI-090': Defect(
        row_id='CI-090',
        summary='The FK constraint name is synthesized from a Postgres default, not read.',
        why_it_is_wrong=(
            'The OpenAPI source fabricates "<table>_<column>_fkey" because the document carries no '
            'constraint name. That is a pg DEFAULT, not a recoverable fact, and it is provably '
            'wrong for any hand-named constraint: the testbed names this one order_lines_order_fk '
            'in SQL, and castiron reports order_lines_order_id_fkey. Harmless for the Pydantic '
            'emitter (which never renders it), but a SQLAlchemy/DDL emitter would emit a name= that '
            'does not match the database and `castiron check` would then report drift that does not '
            'exist -- a broken build for a user who changed nothing. pg_constraint.conname settles '
            'it in CI-010/CI-011.'
        ),
    ),
}


# ---------------------------------------------------------------------------
# Inputs.
# ---------------------------------------------------------------------------

#: CI-005's hand-authored document. ``origin='synthetic'`` is **load-bearing**, not a label: the
#: fixture contains a shape PostgREST cannot emit (CI-076/SEED-F1), so it must never be cited as
#: evidence about PostgREST. The corpus's evidence about PostgREST comes from the two captures.
OPENAPI_FIXTURE = InputFamily(
    family_id='openapi-fixture',
    input_path=FIXTURE_INPUT,
    provenance_path=None,
    schema='public',
    origin='synthetic',
)

#: The corpus's centre of gravity: 26 tables, 3 enums, 11 functions, a cross-schema enum
#: collision, a dangling FK, and the view-classification defect, in real PostgREST encodings.
TESTBED_PUBLIC = InputFamily(
    family_id='testbed-public',
    input_path=INPUTS_DIR / 'testbed-public.openapi.json',
    provenance_path=INPUTS_DIR / 'testbed-public.provenance.json',
    schema='public',
    origin='captured',
)

#: A second document reaching a different schema (``Accept-Profile`` / ``--schema``), and the
#: corpus's only fully-``asserted`` capture — the control with no known-wrong region at all.
TESTBED_INVENTORY = InputFamily(
    family_id='testbed-inventory',
    input_path=INPUTS_DIR / 'testbed-inventory.openapi.json',
    provenance_path=INPUTS_DIR / 'testbed-inventory.provenance.json',
    schema='inventory',
    origin='captured',
)

#: Hand-authored identifier-hostile shapes. Synthetic on purpose: the real ``edge`` schema is
#: excluded by the testbed's own contract ("never a golden input" — its document form is not
#: contractual, so a PostgREST upgrade could move it), and a synthetic input lets the corpus own
#: exactly the shapes it wants. It is the **only** static coverage of CI-080 and CI-085.
SYNTHETIC_TORTURE = InputFamily(
    family_id='synthetic-torture',
    input_path=INPUTS_DIR / 'synthetic-torture.openapi.json',
    provenance_path=INPUTS_DIR / 'synthetic-torture.provenance.json',
    schema='public',
    origin='synthetic',
)

#: Every input family, in case-table order.
FAMILIES: tuple[InputFamily, ...] = (OPENAPI_FIXTURE, TESTBED_PUBLIC, TESTBED_INVENTORY, SYNTHETIC_TORTURE)


# ---------------------------------------------------------------------------
# Tier A — the full-text goldens.
# ---------------------------------------------------------------------------

#: The shape-changing end of the config space. Measured on the ``public`` capture: 1 659 lines /
#: 136 classes against ``default``'s 1 392 / 110. It is the one committed file where a config
#: *interaction* is legible to a human; the manifest guards the other 126 points by hash.
_MAXIMAL_EMITTER = EmitterConfig(
    add_null_parent_classes=True,
    singular_names=True,
    disable_model_prefix_protection=True,
)
_MAXIMAL_SOURCE = SourceOptions(infer_generated_primary_keys=True, disable_model_prefix_protection=True)

CASES: tuple[CorpusCase, ...] = (
    CorpusCase(
        case_id='openapi-fixture-default',
        family=OPENAPI_FIXTURE,
        source_options=SourceOptions(),
        emitter_config=EmitterConfig(),
        status='characterized',
        defects=('CI-076', 'CI-090'),
        compiles=True,
        # Points at CI-005's committed golden rather than duplicating 14 KB of identical bytes.
        golden_module=FIXTURE_GOLDEN_MODULE,
        golden_ir=GOLDEN_DIR / 'openapi-fixture' / 'ir.json',
    ),
    CorpusCase(
        case_id='testbed-public-default',
        family=TESTBED_PUBLIC,
        source_options=SourceOptions(),
        emitter_config=EmitterConfig(),
        status='characterized',
        defects=('CI-075', 'CI-084', 'CI-090'),
        compiles=True,
        golden_module=GOLDEN_DIR / 'testbed-public' / 'default.py.txt',
        golden_ir=GOLDEN_DIR / 'testbed-public' / 'ir.json',
    ),
    CorpusCase(
        case_id='testbed-public-maximal',
        family=TESTBED_PUBLIC,
        source_options=_MAXIMAL_SOURCE,
        emitter_config=_MAXIMAL_EMITTER,
        status='characterized',
        defects=('CI-075', 'CI-084', 'CI-090'),
        compiles=True,
        golden_module=GOLDEN_DIR / 'testbed-public' / 'maximal.py.txt',
        # A DIFFERENT IR from `testbed-public-default`: both source options are flipped, and the
        # IR is a function of (document, schema, source_options). One golden per distinct IR.
        golden_ir=GOLDEN_DIR / 'testbed-public' / 'ir.maximal.json',
    ),
    CorpusCase(
        case_id='testbed-inventory-default',
        family=TESTBED_INVENTORY,
        source_options=SourceOptions(),
        emitter_config=EmitterConfig(),
        # The control: a real captured document with NO known-wrong region. It has no foreign
        # keys at all, so not even CI-090 reaches it -- which is what makes `asserted` meaningful
        # here rather than merely unexamined.
        status='asserted',
        defects=(),
        compiles=True,
        golden_module=GOLDEN_DIR / 'testbed-inventory' / 'default.py.txt',
        golden_ir=GOLDEN_DIR / 'testbed-inventory' / 'ir.json',
    ),
    CorpusCase(
        case_id='synthetic-torture-default',
        family=SYNTHETIC_TORTURE,
        source_options=SourceOptions(),
        emitter_config=EmitterConfig(),
        status='characterized',
        defects=('CI-085',),
        # ⚠ Deliberately False. castiron emits a module that does not parse, and the corpus
        # asserts that EXACTLY -- so the day it starts parsing, this goes red and names the rows.
        compiles=False,
        golden_module=GOLDEN_DIR / 'synthetic-torture' / 'default.py.txt',
        golden_ir=GOLDEN_DIR / 'synthetic-torture' / 'ir.json',
    ),
)

#: The literal case count. A corpus that silently collects nothing is CI-083 with a friendlier
#: face: the suite stays green and every golden test simply did not exist. Changing the corpus
#: size must be a deliberate edit to this number, never a silent consequence.
EXPECTED_CASE_COUNT = 5

#: The literal manifest row count: 2**7 config points, enumerated.
EXPECTED_MANIFEST_ROWS = 128


def case_by_id(case_id: str) -> CorpusCase:
    """Return the case with ``case_id``.

    Args:
        case_id: The case id to look up.

    Returns:
        The matching :class:`CorpusCase`.

    Raises:
        KeyError: No case carries that id.
    """
    for case in CASES:
        if case.case_id == case_id:
            return case
    raise KeyError(f'No corpus case with id {case_id!r}; known ids: {[c.case_id for c in CASES]}')


def fingerprint_path(family: InputFamily) -> Path:
    """Return the fingerprint manifest path for an input family.

    Args:
        family: The input family.

    Returns:
        ``fingerprints/<family_id>.fingerprints.txt``.
    """
    return FINGERPRINT_DIR / f'{family.family_id}.fingerprints.txt'
