"""``castiron gen`` end to end.

The whole file runs offline. CI-005's hard fetch/parse split (CI5-D3) means a local
``--from ./openapi.json`` exercises the entire pipeline -- source, IR, emitter, write path,
summary -- with **zero HTTP mocking**; only the four tests that are explicitly about the
network patch ``urlopen``.
"""

import json
import logging
import sys
from pathlib import Path
from types import ModuleType, TracebackType
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request

import pytest
from click.testing import CliRunner, Result

import castiron
from castiron.cli import cli
from castiron.cli.output import format_size
from castiron.cli.pipeline import source_origin
from castiron.emitters.base import parse_header_version
from castiron.ir import Schema
from castiron.sources import SourceFetchError, SourceParseError, build_schema_from_document

SECRET = 'eyJhbGciOiJIUzI1NiJ9-SUPERSECRET'


def run(runner: CliRunner, *args: str, **kwargs: Any) -> Result:
    return runner.invoke(cli, ['gen', *args], **kwargs)


class FakeResponse:
    """The minimal ``urlopen`` return value ``fetch_openapi_document`` uses."""

    def __init__(self, body: bytes) -> None:
        self._body = body

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> 'FakeResponse':
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool:
        return False


# ---------------------------------------------------------------------------
# The Phase-0 exit criterion, executed offline.
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestExitCriterion:
    def test_it_writes_the_committed_golden_byte_for_byte(
        self, runner: CliRunner, project: Path, openapi_golden_text: str
    ) -> None:
        # The golden is exactly PydanticEmitter(EmitterConfig()).emit(...) with all defaults, so
        # this is a byte-level proof that the CLI's write path does not alter emitter output.
        #
        # ⚠ Split in two by CI-021a, and the split is the point. The golden pins its recorded
        # castiron version to GOLDEN_TOOL_VERSION so that semantic-release rewriting
        # `__version__` in a release commit cannot turn `main` red. A real `castiron gen` records
        # the INSTALLED version -- so line 1 is asserted against `castiron.__version__` and
        # everything from line 2 on is asserted byte-for-byte against the golden. Between them
        # the two halves cover every byte the CLI wrote, with nothing normalized away.
        result = run(runner, '--from', 'openapi.json', '--emit', 'pydantic', '--output', 'out')
        assert result.exit_code == 0, result.output
        written = (project / 'out' / 'schema.py').read_text(encoding='utf-8')
        assert parse_header_version(written) == castiron.__version__
        assert written.split('\n', 1)[1] == openapi_golden_text.split('\n', 1)[1]

    def test_the_written_file_records_the_running_castiron_version(self, runner: CliRunner, project: Path) -> None:
        # The provenance contract a user's `castiron check` (CI-021b) will read back: the version
        # in the file is the version that wrote it, with no flag and no configuration involved.
        result = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert result.exit_code == 0, result.output
        written = (project / 'out' / 'schema.py').read_text(encoding='utf-8')
        assert written.startswith(f'# Generated by castiron {castiron.__version__}\n')
        assert parse_header_version(written) == castiron.__version__

    def test_the_summary_names_the_counts_and_the_file(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert 'castiron: read 6 tables, 1 enum and 4 functions from openapi.json' in result.stdout
        assert f'castiron: wrote {Path("out") / "schema.py"} (' in result.stdout

    def test_running_twice_produces_identical_bytes(self, runner: CliRunner, project: Path) -> None:
        first = run(runner, '--from', 'openapi.json', '--output', 'out')
        written = (project / 'out' / 'schema.py').read_bytes()
        second = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert (first.exit_code, second.exit_code) == (0, 0)
        assert (project / 'out' / 'schema.py').read_bytes() == written

    def test_the_written_module_is_valid_python_and_instantiable(self, runner: CliRunner, project: Path) -> None:
        assert run(runner, '--from', 'openapi.json', '--output', 'out').exit_code == 0
        source = (project / 'out' / 'schema.py').read_text(encoding='utf-8')
        module = ModuleType('castiron_cli_generated')
        sys.modules[module.__name__] = module
        try:
            exec(compile(source, '<castiron-generated>', 'exec'), module.__dict__)
            product = module.__dict__['ProductsBaseSchema'](id=1, name='Anvil')
            assert product.name == 'Anvil'
        finally:
            del sys.modules[module.__name__]

    def test_the_output_directory_is_created_when_missing(self, runner: CliRunner, project: Path) -> None:
        assert run(runner, '--from', 'openapi.json', '--output', 'deep/nested').exit_code == 0
        assert (project / 'deep' / 'nested' / 'schema.py').is_file()

    def test_the_default_output_directory_is_the_cwd(self, runner: CliRunner, project: Path) -> None:
        assert run(runner, '--from', 'openapi.json').exit_code == 0
        assert (project / 'schema.py').is_file()


# ---------------------------------------------------------------------------
# Source dispatch: URL vs. local document.
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestSourceDispatch:
    def test_the_local_path_never_touches_the_fetcher(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def explode(*args: Any, **kwargs: Any) -> Any:
            raise AssertionError('the offline path must not open a socket')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', explode)
        assert run(runner, '--from', 'openapi.json', '--output', 'out').exit_code == 0

    def test_a_url_is_handed_to_the_openapi_source_with_every_parsed_option(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_document: dict[str, Any],
    ) -> None:
        seen: dict[str, Any] = {}

        def fake_load(url: str, **kwargs: Any) -> Schema:
            seen['url'] = url
            seen.update(kwargs)
            return build_schema_from_document(openapi_fixture_document)

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', fake_load)
        result = run(
            runner,
            '--from',
            'https://abcdefgh.supabase.co',
            '--key',
            SECRET,
            '--schema',
            'billing',
            '--timeout',
            '7.5',
            '--infer-generated-primary-keys',
            '--output',
            'out',
        )
        assert result.exit_code == 0, result.output
        assert seen == {
            'url': 'https://abcdefgh.supabase.co',
            'key': SECRET,
            'schema': 'billing',
            'timeout': 7.5,
            'infer_generated_primary_keys': True,
            'disable_model_prefix_protection': False,
        }

    def test_the_summary_reports_the_normalized_rest_root(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_document: dict[str, Any],
    ) -> None:
        monkeypatch.setattr(
            'castiron.cli.pipeline.load_openapi_schema',
            lambda url, **kwargs: build_schema_from_document(openapi_fixture_document),
        )
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', '--output', 'out')
        assert 'from https://abcdefgh.supabase.co/rest/v1/' in result.stdout

    def test_the_key_reaches_the_fetcher_from_the_environment(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        # The only test that walks env -> CLI -> source -> fetcher.
        captured: list[Request] = []

        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            captured.append(request)
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        monkeypatch.setenv('CASTIRON_KEY', SECRET)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', '--output', 'out')
        assert result.exit_code == 0, result.output
        assert captured[0].full_url == 'https://abcdefgh.supabase.co/rest/v1/'
        assert captured[0].get_header('Apikey') == SECRET
        assert captured[0].get_header('Authorization') == f'Bearer {SECRET}'

    def test_the_supabase_key_variable_is_the_fallback(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        captured: list[Request] = []

        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            captured.append(request)
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        monkeypatch.setenv('SUPABASE_KEY', SECRET)
        monkeypatch.setenv('SUPABASE_URL', 'https://abcdefgh.supabase.co')
        assert run(runner, '--output', 'out').exit_code == 0
        assert captured[0].get_header('Apikey') == SECRET

    def test_castiron_key_wins_over_supabase_key(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        captured: list[Request] = []

        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            captured.append(request)
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        monkeypatch.setenv('CASTIRON_KEY', SECRET)
        monkeypatch.setenv('SUPABASE_KEY', 'the-other-project-key')
        assert run(runner, '--from', 'https://abcdefgh.supabase.co', '--output', 'out').exit_code == 0
        assert captured[0].get_header('Apikey') == SECRET

    def test_a_local_document_that_is_not_json_fails_with_exit_one(self, runner: CliRunner, project: Path) -> None:
        (project / 'broken.json').write_text('{not json', encoding='utf-8')
        result = run(runner, '--from', 'broken.json')
        assert result.exit_code == 1
        assert 'not valid JSON' in result.output

    def test_a_local_document_that_is_not_an_object_fails_with_exit_one(self, runner: CliRunner, project: Path) -> None:
        (project / 'list.json').write_text('[1, 2]', encoding='utf-8')
        result = run(runner, '--from', 'list.json')
        assert result.exit_code == 1
        assert 'not an object' in result.output

    def test_a_local_document_that_cannot_be_decoded_fails_with_exit_one(
        self, runner: CliRunner, project: Path
    ) -> None:
        (project / 'binary.json').write_bytes(b'\xff\xfe\x00')
        result = run(runner, '--from', 'binary.json')
        assert result.exit_code == 1
        assert 'Could not read' in result.output


# ---------------------------------------------------------------------------
# Usage errors (exit 2).
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestUsageErrors:
    def test_a_missing_source_names_all_three_ways_to_supply_one(self, runner: CliRunner, project: Path) -> None:
        result = run(runner)
        assert result.exit_code == 2
        for mention in ('--from', 'CASTIRON_FROM', '[tool.castiron]'):
            assert mention in result.output

    def test_a_source_that_is_neither_a_url_nor_a_file_is_a_usage_error(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'nope.json')
        assert result.exit_code == 2
        assert 'neither a URL nor an existing file' in result.output
        # Deliberately not silently prepended with https://.
        assert 'https://' in result.output

    def test_an_unknown_emitter_lists_the_registered_ones(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--emit', 'nope')
        assert result.exit_code == 2
        assert 'pydantic' in result.output

    def test_filename_with_more_than_one_emitter_is_a_usage_error(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--emit', 'pydantic', '--emit', 'pydantic', '--filename', 'x.py')
        assert result.exit_code == 2
        assert '--filename applies to a single-emitter run' in result.output

    def test_an_empty_emitter_list_is_a_usage_error(self, runner: CliRunner, project: Path) -> None:
        (project / 'pyproject.toml').write_text('[tool.castiron]\nemit = []\n', encoding='utf-8')
        result = run(runner, '--from', 'openapi.json')
        assert result.exit_code == 2
        assert 'No emitters selected' in result.output

    def test_a_nonexistent_config_file_is_a_usage_error(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--config', 'nope.toml', '--from', 'openapi.json')
        assert result.exit_code == 2


# ---------------------------------------------------------------------------
# Failure mapping (exit 1 / 70).
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestFailureMapping:
    @pytest.mark.parametrize('error', [SourceFetchError, SourceParseError])
    def test_a_source_failure_exits_one(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch, error: type[Exception]
    ) -> None:
        def fail(url: str, **kwargs: Any) -> Schema:
            raise error('the source said no')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', fail)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co')
        assert result.exit_code == 1
        assert 'the source said no' in result.output

    def test_a_real_network_failure_exits_one_with_the_hint_worthy_message(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            raise URLError('nodename nor servname provided')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', 'https://typo.supabase.co')
        assert result.exit_code == 1
        assert 'Could not reach https://typo.supabase.co/rest/v1/' in result.output

    @pytest.mark.parametrize('malformed', ['http://[::1', 'https://exa℀mple.com/'])
    def test_a_malformed_url_is_the_users_typo_not_a_castiron_bug(
        self, runner: CliRunner, project: Path, malformed: str
    ) -> None:
        # CI-089. Against main this is exit **70** with "internal error (ValueError: Invalid IPv6
        # URL) ... This is a bug in castiron, please report it at .../issues" -- a user who
        # mistyped a bracket was told to open an issue. `urlsplit` raised out of two unguarded
        # places: `looks_like_url` (which runs first) and `normalize_postgrest_url`.
        result = run(runner, '--from', malformed)
        assert result.exit_code == 1
        assert 'Could not parse' in result.output
        assert malformed in result.output
        assert 'This is a bug in castiron' not in result.output
        # The hint has to fire: naming the URL without saying what a --from may be leaves the
        # user exactly as stuck as exit 70 did.
        assert '--from takes a Supabase project URL' in result.output

    def test_a_malformed_url_carrying_a_key_leaks_neither_the_key_nor_the_query_secret(
        self, runner: CliRunner, project: Path
    ) -> None:
        # Both surfaces at once, because this message is new: the --key value and a credential
        # parameter inside the malformed URL that the message quotes back verbatim.
        result = run(runner, '--from', f'http://[::1/?apikey={SECRET}', '--key', SECRET, '--debug')
        assert result.exit_code == 1
        assert SECRET not in result.output
        assert 'apikey=***' in result.output

    def test_an_unexpected_exception_exits_seventy_without_a_traceback(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def boom(url: str, **kwargs: Any) -> Schema:
            raise RuntimeError('a castiron bug')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', boom)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co')
        assert result.exit_code == 70
        assert 'internal error (RuntimeError' in result.output
        assert 'This is a bug' in result.output
        assert 'Traceback' not in result.output

    def test_debug_prints_a_redacted_traceback_and_still_exits_seventy(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # CI-062. Against main this exits 1 with the interpreter's own unredacted traceback;
        # castiron now prints it, through `redact`, and keeps the documented exit code.
        def boom(url: str, **kwargs: Any) -> Schema:
            raise RuntimeError(f'a castiron bug on {url}?service_role_key={SECRET}')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', boom)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', '--debug')
        assert result.exit_code == 70
        assert 'Traceback (most recent call last)' in result.stderr  # not vacuous
        assert 'RuntimeError: a castiron bug' in result.stderr
        assert SECRET not in result.stderr
        assert SECRET not in result.output

    def test_the_debug_traceback_of_a_chained_failure_is_redacted(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The reachable shape: a bug raised *while* a SourceFetchError is being handled. The
        # `Error:` line is clean either way; the chained block below it was not.
        def boom(url: str, **kwargs: Any) -> Schema:
            try:
                raise SourceFetchError(f'{url}?apikey={SECRET} failed')
            except SourceFetchError:
                raise RuntimeError('inner blew up while handling the fetch failure')  # noqa: B904

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', boom)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', '--debug', '--key', SECRET)
        assert result.exit_code == 70
        assert 'During handling of the above exception' in result.stderr  # not vacuous
        assert SECRET not in result.stderr
        assert SECRET not in result.output

    def test_no_overwrite_with_an_existing_target_exits_one(self, runner: CliRunner, project: Path) -> None:
        (project / 'schema.py').write_text('mine\n', encoding='utf-8')
        result = run(runner, '--from', 'openapi.json', '--no-overwrite')
        assert result.exit_code == 1
        assert 'already exists' in result.output
        assert (project / 'schema.py').read_text(encoding='utf-8') == 'mine\n'

    def test_two_emitters_writing_the_same_file_exits_one(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--emit', 'pydantic', '--emit', 'pydantic')
        assert result.exit_code == 1
        assert 'same path' in result.output

    def test_a_traversing_filename_exits_one(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--filename', '../escape.py', '--output', 'out')
        assert result.exit_code == 1
        assert not (project / 'escape.py').exists()


# ---------------------------------------------------------------------------
# Secrets.
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestSecrets:
    def test_a_query_string_key_is_redacted_out_of_an_error(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # normalize_postgrest_url preserves the query string and the source embeds the target
        # in its error message, so this is a genuine, reachable leak path.
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            raise URLError('down')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', f'https://x.supabase.co/rest/v1/?apikey={SECRET}')
        assert result.exit_code == 1
        assert SECRET not in result.output
        assert 'apikey=***' in result.output

    @pytest.mark.parametrize('name', ['apikey', 'service_role_key'])
    def test_a_query_string_key_is_redacted_out_of_the_summary(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
        name: str,
    ) -> None:
        # An **exit-0** printed surface: the run summary names the origin, so a secret that only
        # leaks on success would never show up in a failure-shaped test.
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', f'https://x.supabase.co/rest/v1/?{name}={SECRET}', '--output', 'out')
        assert result.exit_code == 0, result.output
        assert SECRET not in result.output
        assert f'{name}=***' in result.stdout

    def test_the_literal_key_value_never_reaches_the_terminal(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fail(url: str, **kwargs: Any) -> Schema:
            raise SourceFetchError(f'{url} returned HTTP 401 while presenting {kwargs["key"]}')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', fail)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', SECRET)
        assert result.exit_code == 1
        assert SECRET not in result.output
        assert 'HTTP 401' in result.output

    # ⚠ Every case above ran at the default verbosity, which is how the original leak shipped:
    # `fetch` logs the normalized target at DEBUG and the log handler had no redaction, so
    # -vv/--debug printed `?apikey=...` in full -- the very output castiron's internal-error
    # message tells users to paste into an issue. The verbosity flags are now part of the
    # matrix rather than an afterthought.
    @pytest.mark.parametrize('verbosity', [[], ['-v'], ['-vv'], ['--debug'], ['-vv', '--debug']])
    @pytest.mark.parametrize(
        ('source', 'expected_exit'),
        [
            (f'https://x.supabase.co/rest/v1/?apikey={SECRET}', 1),
            # CI-066: the old pattern anchored the credential word to the `?`/`&`, so every
            # prefixed spelling printed in full -- and a service-role key is the worst one.
            (f'https://x.supabase.co/rest/v1/?service_role_key={SECRET}', 1),
            # CI-066/CI066-Q1: a userinfo URL is refused at the boundary (exit 2) rather than
            # handed to an HTTP client that quotes the password back in its InvalidURL.
            (f'https://user:{SECRET}@x.supabase.co/rest/v1/', 2),
        ],
        ids=['apikey', 'service_role_key', 'url-userinfo'],
    )
    def test_a_query_string_key_is_redacted_at_every_verbosity(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        verbosity: list[str],
        source: str,
        expected_exit: int,
    ) -> None:
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            raise URLError('down')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', source, *verbosity)
        assert result.exit_code == expected_exit
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    @pytest.mark.parametrize('verbosity', [[], ['-v'], ['-vv'], ['--debug']])
    def test_the_literal_key_is_redacted_at_every_verbosity(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
        verbosity: list[str],
    ) -> None:
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            logging.getLogger('castiron.sources.openapi.fetch').debug(f'presenting {SECRET}')
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', SECRET, '--output', 'out', *verbosity)
        assert result.exit_code == 0, result.output
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    def test_the_debug_fetch_line_is_redacted(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The exact reproduction: castiron.sources.openapi.fetch logs the normalized target,
        # and normalize_postgrest_url keeps the query string.
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            raise URLError('down')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', f'https://x.supabase.co/rest/v1/?apikey={SECRET}', '--debug')
        assert 'Fetching the OpenAPI document from https://x.supabase.co/rest/v1/?apikey=***' in result.stderr

    @pytest.mark.parametrize('name', ['apikey', 'service_role_key'])
    def test_a_typo_that_drops_the_scheme_is_redacted_out_of_the_usage_error(
        self, runner: CliRunner, project: Path, name: str
    ) -> None:
        # `x.supabase.co/...` has no scheme, so it is neither a URL nor a file and click echoes
        # the value back verbatim. Omitting `https://` while pasting a project URL is a very
        # plausible typo, and that pasted URL carries the key -- so this path really does
        # print a secret. It was the one printed surface with no test on it.
        result = run(runner, '--from', f'x.supabase.co/rest/v1/?{name}={SECRET}')
        assert result.exit_code == 2
        assert 'neither a URL nor an existing file' in result.output
        assert SECRET not in result.output
        assert f'{name}=***' in result.output

    # ⚠ CI-068, folded in by captain ruling. The sibling of the test above: the same echo, but
    # with the secret in a schemeless `user:password@host` rather than a query parameter.
    # `redact` cannot anchor on that shape (a bare `a:b@c` is ordinary prose), so `gen` sends
    # this one surface through `redact_source` instead. Note PR #8 created an asymmetry this
    # closes: `postgresql://user:pw@host` is safely refused while the schemeless
    # `postgres:user:pw@host` -- the shape psql connection strings circulate in -- printed
    # in full.
    @pytest.mark.parametrize(
        'source',
        [
            f'postgres:{SECRET}@db.x.supabase.co:5432/postgres',
            f'user:{SECRET}@x.supabase.co',
        ],
    )
    def test_a_schemeless_userinfo_source_is_redacted_out_of_the_usage_error(
        self, runner: CliRunner, project: Path, source: str
    ) -> None:
        result = run(runner, '--from', source)
        assert result.exit_code == 2
        assert 'neither a URL nor an existing file' in result.output  # not vacuous
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    def test_a_schemeless_userinfo_source_from_the_environment_is_redacted_too(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The secret does NOT have to be on the command line, so "it was in the shell history
        # anyway" does not hold: CASTIRON_FROM, SUPABASE_URL and a `from = "..."` in
        # pyproject.toml all reach the same echo.
        monkeypatch.setenv('SUPABASE_URL', f'postgres:{SECRET}@db.x.supabase.co:5432/postgres')
        result = run(runner)
        assert result.exit_code == 2
        assert SECRET not in result.output

    def test_a_schemeless_userinfo_source_from_the_config_file_is_redacted_too(
        self, runner: CliRunner, project: Path
    ) -> None:
        (project / 'pyproject.toml').write_text(
            f'[tool.castiron]\nfrom = "postgres:{SECRET}@db.x.supabase.co:5432/postgres"\n', encoding='utf-8'
        )
        result = run(runner, '--output', 'out')
        assert result.exit_code == 2
        assert SECRET not in result.output

    @pytest.mark.parametrize(
        'source',
        [
            f'nosuchfile-{SECRET}.json',
            f'nope.json?bearerthing={SECRET}',
        ],
    )
    def test_the_key_is_redacted_out_of_the_usage_error_too(
        self, runner: CliRunner, project: Path, source: str
    ) -> None:
        # ⚠ Round 3. Surface 7 with a --key in play. `redact_source` replaced `redact(source,
        # key)` and dropped the key, so the API key printed in full here -- a leak introduced by
        # the commit that closed one, on the same surface. Every CI-068 test ran without --key.
        result = run(runner, '--from', source, '--key', SECRET)
        assert result.exit_code == 2
        assert 'neither a URL nor an existing file' in result.output  # not vacuous
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    @pytest.mark.parametrize(
        'source',
        [
            f'https://user:{SECRET}@[::1',
            f'https://u:{SECRET}@h:notaport/',
        ],
    )
    def test_a_malformed_userinfo_url_does_not_escape_the_error_boundary(
        self, runner: CliRunner, project: Path, source: str
    ) -> None:
        # ⚠ Round 3. The option callback runs in click's make_context, outside
        # `cli_error_handling`. An unhandled ValueError there printed a raw UNREDACTED traceback
        # and exited 1 -- regressing CI6-D9's exit-code contract and CI-062, which is commit 2 of
        # this same PR. Measured against a real process: on main rc=70 with no traceback, on the
        # unpatched branch rc=1 with the full unredacted traceback on stderr.
        #
        # ⚠ The assertion is `result.exception`, NOT `'Traceback' not in result.output`. Measured:
        # CliRunner swallows an escaping exception into `result.exception` and leaves `output`
        # EMPTY, so the obvious spelling of this test passes against the bug. Every path out of
        # the CLI is a SystemExit; anything else escaped the boundary.
        result = run(runner, '--from', source)
        assert isinstance(result.exception, SystemExit), f'{type(result.exception).__name__} escaped the CLI'
        assert result.exit_code == 2
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    def test_a_postgres_dsn_is_not_refused_at_the_boundary(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # ⚠ Fix round. The boundary refusal is scoped to the schemes castiron fetches over HTTP.
        # A postgresql:// DSN is the canonical libpq connection string that CI-010's live-database
        # source will consume, so it must reach the source layer -- where it fails as an unknown
        # source, not as a usage error -- with its password still masked out of the message.
        result = run(runner, '--from', f'postgresql://postgres:{SECRET}@db.x.supabase.co:5432/postgres')
        assert 'userinfo' not in result.output  # the boundary did NOT refuse it
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    def test_the_internal_error_message_is_redacted(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # An unexpected exception is a castiron bug, and its str() is echoed to the user with
        # an invitation to paste it into an issue -- so it is a printed surface like any other.
        def boom(url: str, **kwargs: Any) -> Schema:
            raise RuntimeError(f'{url}?apikey={SECRET} broke while presenting {kwargs["key"]}')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', boom)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', SECRET)
        assert result.exit_code == 70
        assert 'internal error (RuntimeError' in result.output
        assert SECRET not in result.output

    def test_an_exception_logged_by_a_source_is_redacted_at_default_verbosity(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The forward risk CI-061 exists for: no source writes `logger.exception` today, but
        # the moment one does, its traceback prints at ERROR -- above the default WARNING
        # threshold, with no --debug asked for.
        def fail(url: str, **kwargs: Any) -> Schema:
            try:
                raise RuntimeError(f'GET {url}?apikey={SECRET} failed')
            except RuntimeError:
                logging.getLogger('castiron.sources.openapi.fetch').exception('the source call failed')
            raise SourceFetchError('Could not reach the source')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', fail)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', SECRET)
        assert result.exit_code == 1
        assert 'Traceback (most recent call last)' in result.stderr
        assert SECRET not in result.stderr
        assert SECRET not in result.output

    def test_a_key_with_a_trailing_carriage_return_is_trimmed_before_it_is_sent(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        # A key file with Windows line endings -- `--key "$(cat key.txt)"` strips the \n and
        # leaves the \r. Sent as-is it makes `http.client.putheader` raise *before* the socket
        # opens, and that ValueError names the header value with %r, escaping the \r out of
        # existence so `redact` matched nothing and the whole JWT printed at exit 1.
        captured: list[Request] = []

        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            captured.append(request)
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', f'{SECRET}\r\n', '--output', 'out')
        assert result.exit_code == 0, result.output
        assert captured[0].get_header('Apikey') == SECRET
        assert captured[0].get_header('Authorization') == f'Bearer {SECRET}'
        assert SECRET not in result.output

    def test_a_key_from_the_environment_is_trimmed_too(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        # The sanitation hangs off the option, not the command body, so it covers the
        # CASTIRON_KEY / SUPABASE_KEY fallbacks as well.
        captured: list[Request] = []

        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            captured.append(request)
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        monkeypatch.setenv('CASTIRON_KEY', f'{SECRET}\r')
        assert run(runner, '--from', 'https://x.supabase.co', '--output', 'out').exit_code == 0
        assert captured[0].get_header('Apikey') == SECRET

    def test_a_key_with_an_interior_control_character_is_refused_without_echoing_it(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Trimming cannot repair this one, so castiron refuses rather than sending a value it
        # knows an HTTP client will reject with the key in the error text.
        def explode(*args: Any, **kwargs: Any) -> Any:
            raise AssertionError('a refused key must never reach the fetcher')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', explode)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', f'{SECRET}\rmore')
        assert result.exit_code == 2
        assert 'control character' in result.output
        assert 'CRLF' in result.output
        assert SECRET not in result.output

    def test_the_origin_description_is_redacted_even_on_its_defensive_fallback(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # `source_origin` must never raise from the error path, so a normalization failure
        # falls back to echoing the raw --from value -- the one the user pasted, key and all.
        # No CLI run reaches it (normalize only rejects a blank URL, caught earlier), so a
        # direct call is the only way to hold the "every printed string is redacted" line here.
        def explode(url: str) -> str:
            raise SourceFetchError('nope')

        monkeypatch.setattr('castiron.cli.pipeline.normalize_postgrest_url', explode)
        origin = source_origin(f'https://x.supabase.co/rest/v1/?apikey={SECRET}', SECRET)
        assert SECRET not in origin
        assert 'apikey=***' in origin

    def test_a_local_path_that_carries_a_key_is_redacted_in_the_summary(self, runner: CliRunner, project: Path) -> None:
        # A filesystem path is an unlikely place for a key -- but "every printed string is
        # redacted" (CI6-D7) is a claim with no exceptions, and `apikey=` survives a URL
        # pasted into a `curl -o` filename. The local branch printed it verbatim.
        #
        # ⚠ CI-067: the separator is `&`, NOT `?`. This line creates a real file, and `?` is one
        # of Windows' reserved filename characters (< > : " / \ | ? *), so `write_bytes` raises
        # OSError there -- green today only because the CI matrix is ubuntu-latest. `&` is a
        # shell metacharacter, not a filesystem-reserved one, so it is legal on every supported
        # platform, and it is in the leading class of the parameter pattern just like `?`. Do
        # not "restore" the `?`. The `?` spelling keeps its coverage file-free, one test below,
        # through `source_origin(f'dump.json?apikey={SECRET}', SECRET)`.
        weird = project / f'openapi.json&apikey={SECRET}'
        weird.write_bytes((project / 'openapi.json').read_bytes())
        result = run(runner, '--from', weird.name, '--output', 'out')
        assert result.exit_code == 0, result.output
        assert SECRET not in result.output
        assert 'apikey=***' in result.stdout

    # ⚠ CI-066's userinfo class, across the surfaces of §11.2's enumeration. The boundary
    # rejection closes the `--from` route, so the surfaces the *mask* still has to hold are the
    # ones a URL reaches by some other path: a source error carrying a DSN (CI-010's shape), a
    # log record, and the summary origin.
    def test_a_userinfo_url_is_refused_at_exit_two(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Fails against main with exit 1 and `nonnumeric port: '<password>@x.supabase.co'` --
        # the password printed twice, the second time with no scheme in front of it.
        def explode(*args: Any, **kwargs: Any) -> Any:
            raise AssertionError('a refused source must never reach the fetcher')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', explode)
        result = run(runner, '--from', f'https://user:{SECRET}@x.supabase.co')
        assert result.exit_code == 2
        assert 'userinfo' in result.output
        assert SECRET not in result.output
        assert SECRET not in result.stderr

    def test_the_refusal_names_the_shape_and_never_the_value(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', f'https://user:{SECRET}@x.supabase.co')
        assert 'user:password@' in result.output
        assert '--key' in result.output
        assert 'x.supabase.co' not in result.output

    def test_a_userinfo_url_from_the_environment_is_refused_too(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The check hangs off the option, not the command body, so it covers CASTIRON_FROM /
        # SUPABASE_URL and the [tool.castiron] default map as well as the flag.
        monkeypatch.setenv('SUPABASE_URL', f'https://user:{SECRET}@x.supabase.co')
        result = run(runner)
        assert result.exit_code == 2
        assert SECRET not in result.output

    def test_a_userinfo_url_from_the_config_file_is_refused_too(self, runner: CliRunner, project: Path) -> None:
        (project / 'pyproject.toml').write_text(
            f'[tool.castiron]\nfrom = "https://user:{SECRET}@x.supabase.co"\n', encoding='utf-8'
        )
        result = run(runner, '--output', 'out')
        assert result.exit_code == 2
        assert SECRET not in result.output

    def test_a_dsn_password_never_reaches_the_terminal(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The mask ships regardless of the boundary rejection: CI-010's live-DB source will carry
        # postgresql://user:password@host/db in its failures, and this is the surface they print
        # on. Fails against main -- the password prints in full on the `Error:` line at exit 1.
        def fail(url: str, **kwargs: Any) -> Schema:
            raise SourceFetchError(f'Could not connect to postgresql://postgres:{SECRET}@db.x.supabase.co:5432/db')

        monkeypatch.setattr('castiron.cli.pipeline.load_openapi_schema', fail)
        result = run(runner, '--from', 'https://x.supabase.co')
        assert result.exit_code == 1
        assert SECRET not in result.output
        assert 'postgresql://postgres:***@db.x.supabase.co' in result.output

    def test_a_logged_dsn_password_is_redacted_on_a_successful_run(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        # An **exit-0** userinfo surface (§11.2 row 5): a log record at -vv, on a run that
        # succeeds, so nothing about the failure path is doing the work.
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            logging.getLogger('castiron.sources.openapi.fetch').debug(
                f'connected via postgresql://postgres:{SECRET}@db.x.supabase.co:5432/db'
            )
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', 'https://x.supabase.co', '--output', 'out', '-vv')
        assert result.exit_code == 0, result.output
        assert 'postgres:***@db.x.supabase.co' in result.stderr
        assert SECRET not in result.stderr
        assert SECRET not in result.output

    def test_the_summary_origin_masks_a_userinfo_password(self) -> None:
        # §11.2 row 6, reached directly: `source_origin` feeds both the exit-0 summary line and
        # `schema_hint`'s "castiron read ..." line, and the boundary rejection means no CLI run
        # can carry a userinfo URL this far any more.
        origin = source_origin(f'https://user:{SECRET}@x.supabase.co/rest/v1/', None)
        assert SECRET not in origin
        assert 'https://user:***@x.supabase.co' in origin

    def test_the_origin_of_a_local_path_is_redacted_for_the_hint_too(self) -> None:
        # The same value reaches `schema_hint`'s "castiron read <origin>" line through
        # `source_origin`'s non-URL branch, which is a separate return statement.
        assert SECRET not in source_origin(f'dump.json?apikey={SECRET}', SECRET)

    def test_the_key_never_reaches_the_generated_file(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        openapi_fixture_path: Path,
    ) -> None:
        def fake_urlopen(request: Request, timeout: float | None = None) -> FakeResponse:
            return FakeResponse(openapi_fixture_path.read_bytes())

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', fake_urlopen)
        result = run(runner, '--from', 'https://x.supabase.co', '--key', SECRET, '--output', 'out')
        assert result.exit_code == 0, result.output
        assert SECRET not in (project / 'out' / 'schema.py').read_text(encoding='utf-8')

    def test_help_names_the_environment_variables_but_never_a_value(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv('CASTIRON_KEY', SECRET)
        result = run(runner, '--help')
        assert 'CASTIRON_KEY' in result.output
        assert 'SUPABASE_KEY' in result.output
        assert SECRET not in result.output


# ---------------------------------------------------------------------------
# The emitter toggles: every EmitterConfig field is reachable and does something.
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestEmitterToggles:
    @pytest.mark.parametrize(
        ('flag', 'marker', 'present_by_default'),
        [
            ('--no-crud-models', 'class UsersInsert', True),
            ('--no-enums', 'class PublicOrderStatusEnum', True),
            ('--no-foreign-keys', '# Foreign Keys', True),
            ('--singular-names', 'class Product(', False),
            ('--null-parent-classes', 'Parent', False),
        ],
    )
    def test_each_flag_changes_the_emitted_output(
        self, runner: CliRunner, project: Path, flag: str, marker: str, present_by_default: bool
    ) -> None:
        assert run(runner, '--from', 'openapi.json', '--output', 'before').exit_code == 0
        assert run(runner, '--from', 'openapi.json', '--output', 'after', flag).exit_code == 0
        before = (project / 'before' / 'schema.py').read_text(encoding='utf-8')
        after = (project / 'after' / 'schema.py').read_text(encoding='utf-8')
        assert (marker in before) is present_by_default
        assert (marker in after) is not present_by_default

    def test_model_prefix_protection_can_be_disabled(
        self, runner: CliRunner, project: Path, openapi_fixture_document: dict[str, Any]
    ) -> None:
        # The committed fixture has no `model_` column, so the document is extended in place
        # rather than a second fixture being committed.
        document = json.loads(json.dumps(openapi_fixture_document))
        document['definitions']['users']['properties']['model_name'] = {'format': 'text', 'type': 'string'}
        (project / 'prefixed.json').write_text(json.dumps(document), encoding='utf-8')

        assert run(runner, '--from', 'prefixed.json', '--output', 'protected').exit_code == 0
        assert run(runner, '--from', 'prefixed.json', '--output', 'open', '--no-model-prefix-protection').exit_code == 0
        assert 'protected_namespaces' not in (project / 'protected' / 'schema.py').read_text(encoding='utf-8')
        assert 'protected_namespaces' in (project / 'open' / 'schema.py').read_text(encoding='utf-8')

    def test_filename_overrides_the_emitter_default(self, runner: CliRunner, project: Path) -> None:
        assert run(runner, '--from', 'openapi.json', '--output', 'out', '--filename', 'models.py').exit_code == 0
        assert (project / 'out' / 'models.py').is_file()
        assert not (project / 'out' / 'schema.py').exists()


# ---------------------------------------------------------------------------
# Reporting: --dry-run, -q, -v.
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestReporting:
    def test_dry_run_writes_nothing_and_says_so(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '--dry-run')
        assert result.exit_code == 0
        assert not (project / 'out').exists()
        assert 'would write' in result.stdout
        assert '[dry run, nothing written]' in result.stdout

    def test_dry_run_reports_the_size_a_real_run_would_write(self, runner: CliRunner, project: Path) -> None:
        dry = run(runner, '--from', 'openapi.json', '--output', 'out', '--dry-run')
        real = run(runner, '--from', 'openapi.json', '--output', 'out')
        size = dry.stdout.split('(')[-1].split(')')[0]
        assert f'({size})' in real.stdout

    def test_quiet_suppresses_the_summary(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '-q')
        assert result.exit_code == 0
        assert result.stdout == ''
        assert (project / 'out' / 'schema.py').is_file()

    def test_quiet_does_not_suppress_errors(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'nope.json', '-q')
        assert result.exit_code == 2
        assert 'neither a URL nor an existing file' in result.output

    def test_the_identity_pk_warning_is_on_by_default(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert 'integer primary key with no visible default' in result.stderr
        assert '--infer-generated-primary-keys' in result.stderr

    def test_the_identity_pk_warning_is_silenced_by_the_flag(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '--infer-generated-primary-keys')
        assert 'integer primary key with no visible default' not in result.stderr

    def test_verbose_shows_the_openapi_fidelity_note(self, runner: CliRunner, project: Path) -> None:
        quiet_run = run(runner, '--from', 'openapi.json', '--output', 'a')
        loud_run = run(runner, '--from', 'openapi.json', '--output', 'b', '-v')
        assert 'no database connection' not in quiet_run.stderr
        assert 'no database connection' in loud_run.stderr

    def test_double_verbose_adds_debug_provenance(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '-vv')
        assert 'DEBUG castiron.cli.pipeline' in result.stderr

    def test_debug_implies_debug_logging(self, runner: CliRunner, project: Path) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '--debug')
        assert 'DEBUG castiron.cli.pipeline' in result.stderr

    @pytest.mark.parametrize(('size', 'expected'), [(0, '0 B'), (999, '999 B'), (1000, '1.0 kB'), (14200, '14.2 kB')])
    def test_the_size_is_rendered_in_bytes_below_a_kilobyte(self, size: int, expected: str) -> None:
        assert format_size(size) == expected

    def test_repeated_invocations_do_not_stack_log_handlers(self, runner: CliRunner, project: Path) -> None:
        first = run(runner, '--from', 'openapi.json', '--output', 'out')
        second = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert first.stderr.count('integer primary key') == 1
        assert second.stderr.count('integer primary key') == 1


# ---------------------------------------------------------------------------
# The Hint: lines, end to end (spec §3.1's transcripts (b), (c) and (d)).
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestHints:
    @staticmethod
    def _http(monkeypatch: pytest.MonkeyPatch, code: int) -> None:
        def raiser(request: Request, timeout: float | None = None) -> FakeResponse:
            raise HTTPError(request.full_url, code, 'nope', {}, None)  # type: ignore[arg-type] - stdlib accepts None

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', raiser)

    def test_an_unreachable_url_earns_the_from_hint(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def raiser(request: Request, timeout: float | None = None) -> FakeResponse:
            raise URLError('nodename nor servname provided')

        monkeypatch.setattr('castiron.sources.openapi.fetch.urlopen', raiser)
        result = run(runner, '--from', 'https://typo.supabase.co')
        assert result.exit_code == 1
        assert 'Hint: --from takes a Supabase project URL' in result.output

    @pytest.mark.parametrize(
        ('args', 'env', 'expected'),
        [
            (['--key', SECRET], {}, 'the key came from --key'),
            ([], {'CASTIRON_KEY': SECRET}, 'the key came from CASTIRON_KEY'),
            ([], {'SUPABASE_KEY': SECRET}, 'the key came from SUPABASE_KEY'),
            ([], {'CASTIRON_KEY': SECRET, 'SUPABASE_KEY': 'other'}, 'the key came from CASTIRON_KEY'),
            ([], {}, 'no key was given'),
        ],
    )
    def test_a_401_names_where_the_key_came_from(
        self,
        runner: CliRunner,
        project: Path,
        monkeypatch: pytest.MonkeyPatch,
        args: list[str],
        env: dict[str, str],
        expected: str,
    ) -> None:
        # CI6-Q2 accepted the ambient SUPABASE_KEY fallback *because* this hint exists: a user
        # who silently picks up another project's key has no other way to find out.
        self._http(monkeypatch, 401)
        for name, value in env.items():
            monkeypatch.setenv(name, value)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', *args)
        assert result.exit_code == 1
        assert f'Hint: {expected}' in result.output
        assert SECRET not in result.output

    def test_a_403_earns_the_key_hint_too(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        self._http(monkeypatch, 403)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co', '--key', SECRET)
        assert 'Hint: the key came from --key' in result.output

    def test_the_supabase_fallback_hint_says_it_may_be_another_project_s(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        self._http(monkeypatch, 401)
        monkeypatch.setenv('SUPABASE_KEY', SECRET)
        result = run(runner, '--from', 'https://abcdefgh.supabase.co')
        assert 'belongs to this project' in result.output

    def test_an_empty_schema_earns_the_schema_hint_naming_what_was_read(self, runner: CliRunner, project: Path) -> None:
        (project / 'empty.json').write_text('{"swagger":"2.0","definitions":{},"paths":{}}', encoding='utf-8')
        result = run(runner, '--from', 'empty.json', '--schema', 'billing')
        assert result.exit_code == 1
        assert 'Hint: try --schema <name>' in result.output
        assert "'billing'" in result.output
        # §3.1(d) names the document; the engine's message does not, so the hint supplies it.
        assert 'castiron read empty.json' in result.output

    def test_the_hint_never_carries_the_key(
        self, runner: CliRunner, project: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        self._http(monkeypatch, 401)
        result = run(runner, '--from', f'https://x.supabase.co/rest/v1/?apikey={SECRET}', '--key', SECRET)
        assert SECRET not in result.output
        assert SECRET not in result.stderr


@pytest.mark.unit
class TestConfigReporting:
    def test_the_config_file_actually_used_is_reported_at_info(self, runner: CliRunner, project: Path) -> None:
        # Discovery walks up from the cwd implicitly, so "which file did you read" is exactly
        # what -v is for (spec §3.2 note 3) -- it needed -vv before.
        (project / 'pyproject.toml').write_text('[tool.castiron]\nfrom = "openapi.json"\n', encoding='utf-8')
        result = run(runner, '--output', 'out', '-v')
        assert f'Reading [tool.castiron] from {project / "pyproject.toml"}' in result.stderr

    def test_it_is_silent_at_the_default_verbosity(self, runner: CliRunner, project: Path) -> None:
        (project / 'pyproject.toml').write_text('[tool.castiron]\nfrom = "openapi.json"\n', encoding='utf-8')
        result = run(runner, '--output', 'out')
        assert 'Reading [tool.castiron]' not in result.stderr


@pytest.mark.unit
class TestFilenameGuards:
    @pytest.mark.parametrize('value', ['.', '/schema.py', '../escape.py'])
    def test_a_filename_that_escapes_or_names_nothing_exits_one(
        self, runner: CliRunner, project: Path, value: str
    ) -> None:
        result = run(runner, '--from', 'openapi.json', '--output', 'out', '--filename', value)
        assert result.exit_code == 1
        assert 'Refusing to write' in result.output

    def test_a_dot_filename_leaves_the_output_directory_a_directory(self, runner: CliRunner, project: Path) -> None:
        (project / 'out').mkdir()
        assert run(runner, '--from', 'openapi.json', '--output', 'out', '--filename', '.').exit_code == 1
        assert (project / 'out').is_dir()

    def test_a_null_byte_filename_is_a_user_error_not_a_castiron_bug(self, runner: CliRunner, project: Path) -> None:
        # argv cannot carry a NUL, so this arrives through the config file.
        (project / 'pyproject.toml').write_text(
            '[tool.castiron]\nfrom = "openapi.json"\nfilename = "a\\u0000b.py"\n', encoding='utf-8'
        )
        result = run(runner, '--output', 'out')
        assert result.exit_code == 1
        assert 'This is a bug' not in result.output


@pytest.mark.unit
class TestCi128TheEnumClassRenameIsSurfaced:
    """``CI-128``: a repaired or suffixed enum class name is told to the user, not repaired silently.

    Same channel and same voice as the ``CI-085`` column notice -- one aggregated ``castiron: …``
    line on stderr per run, at most three names spelled out. The end-to-end assertion matters
    because the notice is computed from the emitter that is about to run: a unit test on
    ``notices.py`` cannot prove the CLI hands it the names the emitter will actually write.
    """

    #: A PostgREST document whose enum columns carry hostile pg type names in `format`, verbatim --
    #: which is exactly how PostgREST reports them.
    DOCUMENT = {
        'swagger': '2.0',
        'info': {'title': 'PostgREST API', 'version': '11'},
        'definitions': {
            'orders': {
                'type': 'object',
                'properties': {
                    'id': {'type': 'integer', 'format': 'bigint', 'description': 'Note:\nThis is a Primary Key.<pk/>'},
                    'a': {'type': 'string', 'format': 'public.order status', 'enum': ['pending']},
                    'b': {'type': 'string', 'format': 'public.order_status', 'enum': ['shipped']},
                },
            }
        },
        'paths': {'/orders': {'get': {}}},
    }

    def _write_document(self, project: Path) -> None:
        (project / 'hostile.json').write_text(json.dumps(self.DOCUMENT), encoding='utf-8')

    def test_the_notice_names_the_rename_and_its_cause(self, runner: CliRunner, project: Path) -> None:
        self._write_document(project)
        result = run(runner, '--from', 'hostile.json', '--output', 'out')
        assert result.exit_code == 0
        assert 'castiron: 1 enum type is not emitted under the class name' in result.output
        assert 'public.order status -> PublicOrderStatusEnum_2' in result.output
        assert 'PublicOrderStatusEnum is taken by public.order_status' in result.output

    def test_the_written_module_imports_and_binds_both_types(self, runner: CliRunner, project: Path) -> None:
        # The notice is only worth anything if the artifact it describes actually works. Before
        # CI-128 this document produced a SyntaxError at exit 0.
        self._write_document(project)
        assert run(runner, '--from', 'hostile.json', '--output', 'out').exit_code == 0
        text = (project / 'out' / 'schema.py').read_text(encoding='utf-8')
        namespace: dict[str, Any] = {}
        exec(compile(text, '<generated>', 'exec'), namespace)  # noqa: S102 - executing IS the assertion
        assert namespace['PublicOrderStatusEnum']('shipped').value == 'shipped'
        assert namespace['PublicOrderStatusEnum_2']('pending').value == 'pending'
        assert '# original name was "public.order status"' in text

    def test_a_well_behaved_schema_prints_no_enum_notice(self, runner: CliRunner, project: Path) -> None:
        # The counter-witness: the shipped fixture must stay silent, or every user sees the line.
        result = run(runner, '--from', 'openapi.json', '--output', 'out')
        assert result.exit_code == 0
        assert 'not emitted under the class name' not in result.output

    def test_the_notice_stays_quiet_when_enums_are_not_emitted(self, runner: CliRunner, project: Path) -> None:
        self._write_document(project)
        result = run(runner, '--from', 'hostile.json', '--output', 'out', '--no-enums')
        assert result.exit_code == 0
        assert 'not emitted under the class name' not in result.output
