"""Fidelity notices — telling the user what the OpenAPI source could not see.

The OpenAPI/PostgREST source needs no database credentials, and pays for it: unique and
check constraints, identity/generated columns, exact integer widths below ``bigint``, and
function return types are simply not encoded in the document (CI-005 spec §11). Two of
those are invisible to the user until their code misbehaves, so this module surfaces the
one that actually bites:

**PostgREST does not expose ``nextval()``/identity defaults.** Every Supabase project's
``id bigint generated by default as identity`` therefore looks like a plain NOT NULL
integer primary key with no default, and castiron marks it *required* on the Insert model.
The fix is one flag (``--infer-generated-primary-keys``), so the warning fires **once**,
and only when it would actually change the output — CI5-D11 rejected per-column
degradation warnings as noise, and this is deliberately not that.

The second notice (CI-085) is a *rename*, not a fidelity loss: a column name that is legal in
Postgres but unusable as a Pydantic field is repaired, so the attribute the user must type is
not the column name they know. That is a surprise worth one line — and, following the same
CI5-D11 rule, it is **one aggregated warning per run**, not one per column.

The third (CI-128) is the same kind of rename one level up: an enum **class** name that had to be
repaired for identifier legality, or suffixed because another type or class already held it. It
follows the CI-085 notice byte for byte in shape — one aggregated warning, at most three names
spelled out, then ``and N more``. Deliberately not a third mechanism: castiron already had two ways
to tell a user "the name you know is not the name you type", and a third would be one too many.

The fourth (CI-130) is the last member of that family: a **table**'s model class stem, repaired or
suffixed by the same rule. It is the one most likely to be seen, because a table's classes are what
a user imports — and, unlike a column, a table name has no ``Field(alias=...)`` to preserve it, so
the notice plus the in-code comment are the whole record.

The fifth (CI-084) is **not** a rename, and that is what sets it apart from the middle three: it is a
*structural loss*. A foreign key whose target table the API role cannot see leaves castiron nothing
to build a relationship out of, so the column is emitted as a plain value and no nested model is
generated for it. The user cannot tell from the output that anything is missing -- the emitted module
is a perfectly ordinary one -- which is precisely why it is worth a line. It is source-agnostic (the
predicate reads only the IR, and a DDL or single-schema live-DB run reaches the same state), and it
follows CI5-D11 like its siblings: one aggregated warning per run, at most three named.

The sixth (CI-141) is a structural loss of a different kind again: one caused by the **server build**
rather than the schema. PostgREST only started withholding the ``get`` operation for VOLATILE
functions in **13.0.5**; below that the document carries a ``get`` for every ``/rpc/`` path, so
volatility is simply not in it and castiron reports ``volatility`` and ``is_read_only`` as unknown
for every function rather than asserting that every mutation is read-only. Unlike its five siblings
it names **no** individual objects -- the set is always *all* the functions, so a sample would be
misleading -- and its warning takes a second argument, the observed version, because the version and
the remedy are the actionable part of the message.
"""

import logging
from collections.abc import Sequence

from castiron.ir import ConstraintType, Schema
from castiron.ir.build import (
    column_name_is_reserved,
    column_name_reserved_exceptions,
    parse_constraint_definition_for_fk,
)
from castiron.sources.openapi import INTEGER_FAMILY, volatility_is_encoded
from castiron.utils.naming import ClassStem, EnumClass, class_stem_reason, enum_class_reason

logger = logging.getLogger(__name__)

#: Raw type tokens the identity inference applies to. Aliased from the source's own
#: constant rather than re-listed, so the CLI notice and the inference cannot drift.
INTEGER_PK_TYPES = INTEGER_FAMILY

#: How many names a warning spells out before collapsing to "and N more". Shared by every
#: notice that names things, so a wide schema degrades the same way whichever one fires.
MAX_NAMED_TABLES = 3

#: Shown at INFO (``-v``) once per run when the schema came from the OpenAPI source.
OPENAPI_FIDELITY_NOTE = (
    'Read from the OpenAPI source (no database connection): unique/check constraints, constraint '
    'names, identity columns, exact integer widths below bigint, and function return types are not '
    'visible from it.'
)


def identity_pk_candidates(schema: Schema) -> list[str]:
    """Return table names whose sole primary key looks like an un-detected identity column.

    The predicate reads the **IR** — exactly one column with ``primary`` set, NOT NULL, no
    default, not already flagged as identity, and an integer raw type. Known, accepted
    divergence from the source's own inference: the source applies its rule to any
    definition carrying a sole ``<pk/>`` marker, while ``ColumnInfo.primary`` is left
    ``False`` for views (CI5-D14). A view is not a meaningful Insert target, so the warning
    correctly stays quiet for one.

    Args:
        schema: The schema to inspect (treated as read-only).

    Returns:
        The candidate table names, in ``Schema.tables`` order.
    """
    candidates: list[str] = []
    for table in schema.tables:
        primaries = [column for column in table.columns if column.primary]
        if len(primaries) != 1:
            continue
        column = primaries[0]
        if column.nullable() or column.default is not None or column.is_identity:
            continue
        if column.raw_type in INTEGER_PK_TYPES:
            candidates.append(table.name)
    return candidates


def identity_pk_warning(tables: list[str]) -> str:
    """Build the identity-PK warning for ``tables``, naming at most three of them."""
    named = ', '.join(tables[:MAX_NAMED_TABLES])
    if len(tables) > MAX_NAMED_TABLES:
        named = f'{named} and {len(tables) - MAX_NAMED_TABLES} more'
    subject = 'table has' if len(tables) == 1 else 'tables have'
    return (
        f'{len(tables)} {subject} an integer primary key with no visible default ({named}) -- '
        'PostgREST does not expose nextval()/identity defaults, so castiron marks those columns '
        'required on the Insert models. Pass --infer-generated-primary-keys (or set '
        'infer-generated-primary-keys = true) if they are serial/identity columns.'
    )


def repaired_column_names(schema: Schema, *, disable_model_prefix_protection: bool) -> list[tuple[str, str, str]]:
    """Return ``(table, wire_name, python_name)`` for every column repaired for identifier legality.

    ⚠ **The discriminator needs no new IR field, and that is deliberate.**
    :meth:`~castiron.ir.Schema.as_dict` is ``{f.name: … for f in fields(obj)}``, so adding a
    "why was this renamed" field to :class:`~castiron.ir.ColumnInfo` would rewrite every one of the
    six committed ``ir.json`` goldens for a CLI cosmetic. The fact is derivable: ``alias`` is set
    iff the emitted attribute differs from the wire name, and the two shipped predicates say
    whether the *shipped* reserved-word path is what did it.

    **The shipped reserved-word path is excluded on purpose.** A schema with a column named
    ``class`` works today and must not grow a new warning for behaviour that has not changed.
    Only the ``CI-085`` repairs — a leading digit, a space, a hyphen, a leading underscore, an
    NFKC collision — are reported.

    Args:
        schema: The schema that was just loaded (treated as read-only).
        disable_model_prefix_protection: Must match the value the schema was built with, or the
            reserved-word discriminator will mis-classify every ``model_`` column.

    Returns:
        One tuple per repaired column, in ``Schema.tables`` then ``TableInfo.columns`` order.
    """
    repaired: list[tuple[str, str, str]] = []
    for table in schema.tables:
        for column in table.columns:
            if column.alias is None:
                continue
            if column_name_is_reserved(
                column.alias, disable_model_prefix_protection
            ) and not column_name_reserved_exceptions(column.alias):
                continue  # the shipped reserved-word path -- not new, and not noteworthy
            repaired.append((table.name, column.alias, column.name))
    return repaired


def repaired_column_warning(columns: list[tuple[str, str, str]]) -> str:
    """Build the identifier-repair warning for ``columns``, naming at most three of them."""
    named = ', '.join(f'{table}.{wire} -> {python}' for table, wire, python in columns[:MAX_NAMED_TABLES])
    if len(columns) > MAX_NAMED_TABLES:
        named = f'{named} and {len(columns) - MAX_NAMED_TABLES} more'
    subject = 'column name is' if len(columns) == 1 else 'column names are'
    return (
        f'{len(columns)} {subject} not usable as a Python field name and {"was" if len(columns) == 1 else "were"} '
        f'renamed ({named}) -- the original name is preserved on the wire via Field(alias=...), so '
        f'the generated models still read and write the real column; only the attribute you type '
        f'in Python differs.'
    )


def renamed_enum_classes(classes: Sequence[EnumClass]) -> list[EnumClass]:
    """Return the resolved enum classes whose name is not the straight transform of their type name.

    Args:
        classes: Every resolved class, from the emitter's own
            :meth:`~castiron.emitters.PydanticEmitter.enum_classes` — the single authority for what
            was actually written. Re-deriving them here would be a second answer to one question.

    Returns:
        The renamed ones, in emission order. Empty for a well-behaved schema, which is the common
        case and prints nothing.
    """
    return [entry for entry in classes if entry.note is not None]


def renamed_enum_class_warning(classes: list[EnumClass]) -> str:
    """Build the enum class-name warning for ``classes``, naming at most three of them.

    ⚠ **The suffixed case names who took the bare name**, via
    :func:`~castiron.utils.naming.enum_class_reason`. A user who finds ``PublicOrderStatusEnum_2``
    in their models otherwise has no way to discover what holds ``PublicOrderStatusEnum``, and a
    rename you cannot explain is a bug report rather than something to act on.

    Args:
        classes: The renamed classes (already filtered by :func:`renamed_enum_classes`).

    Returns:
        The warning line, in the same voice as :func:`repaired_column_warning`.
    """
    details = [
        f'{entry.enum.schema}.{entry.enum.name} -> {entry.name} ({enum_class_reason(entry, str)})'
        for entry in classes[:MAX_NAMED_TABLES]
    ]
    named = ', '.join(details)
    if len(classes) > MAX_NAMED_TABLES:
        named = f'{named} and {len(classes) - MAX_NAMED_TABLES} more'
    noun = 'enum type is' if len(classes) == 1 else 'enum types are'
    return (
        f'{len(classes)} {noun} not emitted under the class name their Postgres type name suggests '
        f'({named}) -- the original type name is preserved in a comment above each class, so the '
        f'generated module still records which type it came from; only the Python class name differs.'
    )


def renamed_class_stems(stems: Sequence[ClassStem]) -> list[ClassStem]:
    """Return the resolved table stems whose class name is not the straight transform of their name.

    Args:
        stems: Every resolved stem, from the emitter's own
            :meth:`~castiron.emitters.PydanticEmitter.class_stems` — the single authority for what
            was actually written. Re-deriving them here would be a second answer to one question.

    Returns:
        The renamed ones, in emission order. Empty for a well-behaved schema, which is the common
        case and prints nothing.
    """
    return [entry for entry in stems if entry.note is not None]


def renamed_class_stem_warning(stems: list[ClassStem]) -> str:
    """Build the model class-name warning for ``stems``, naming at most three of them.

    ⚠ **Louder in consequence than its enum sibling, and deliberately identical in shape.** A
    repaired *column* keeps its wire name through ``Field(alias=...)``, so nothing about the data is
    lost; a repaired *table* name survives only as the ``# original name was …`` comment, and the
    class the user imports is genuinely called something else.

    Args:
        stems: The renamed stems (already filtered by :func:`renamed_class_stems`).

    Returns:
        The warning line, in the same voice as :func:`renamed_enum_class_warning`.
    """
    details = [
        f'{entry.source} -> {entry.name} ({class_stem_reason(entry, str)})' for entry in stems[:MAX_NAMED_TABLES]
    ]
    named = ', '.join(details)
    if len(stems) > MAX_NAMED_TABLES:
        named = f'{named} and {len(stems) - MAX_NAMED_TABLES} more'
    noun = 'table is' if len(stems) == 1 else 'tables are'
    return (
        f'{len(stems)} {noun} not emitted under the class name their name suggests ({named}) -- the '
        f'original table name is preserved in a comment above each generated class, so the module '
        f'still records which table it came from; only the Python class name differs.'
    )


def dangling_foreign_keys(schema: Schema) -> list[str]:
    """Return ``table.column -> missing_target`` for every FK whose target is not in the schema.

    ⚠ **Source-agnostic, and it needs no new IR field.** The predicate reads only what the IR
    already carries: a ``FOREIGN KEY`` :class:`~castiron.ir.ConstraintInfo` is retained even when
    the builder resolves no edge for it, and its ``constraint_definition`` names the target, which
    the shipped :func:`~castiron.ir.build.parse_constraint_definition_for_fk` parses. Recording the
    dangling target a second time on the IR would be two representations of one fact.

    The discriminator is :attr:`~castiron.ir.ColumnInfo.is_foreign_key`, which since CI-084 is
    ``True`` iff a resolved forward edge names the column -- so a FOREIGN KEY constraint naming a
    column the flag left ``False`` is exactly a dropped relationship.

    Args:
        schema: The schema that was just loaded (treated as read-only).

    Returns:
        One ``'table.column -> target'`` entry per dropped edge, in ``Schema.tables`` then
        ``TableInfo.constraints`` order (deterministic).
    """
    dangling: list[str] = []
    for table in schema.tables:
        for constraint in table.constraints:
            if constraint.type is not ConstraintType.FOREIGN_KEY or constraint.constraint_definition is None:
                continue
            parsed = parse_constraint_definition_for_fk(constraint.constraint_definition)
            if parsed is None:
                continue
            _, target, _ = parsed
            for name in constraint.columns:
                column = next((c for c in table.columns if c.name == name), None)
                if column is not None and not column.is_foreign_key:
                    dangling.append(f'{table.name}.{name} -> {target}')
    return dangling


def dangling_foreign_key_warning(entries: list[str]) -> str:
    """Build the dangling-foreign-key warning for ``entries``, naming at most three of them.

    Args:
        entries: The dropped edges (already collected by :func:`dangling_foreign_keys`).

    Returns:
        The warning line, in the same voice as :func:`renamed_class_stem_warning`.
    """
    named = ', '.join(entries[:MAX_NAMED_TABLES])
    if len(entries) > MAX_NAMED_TABLES:
        named = f'{named} and {len(entries) - MAX_NAMED_TABLES} more'
    subject = 'foreign key points' if len(entries) == 1 else 'foreign keys point'
    return (
        f'{len(entries)} {subject} at a table this schema does not contain ({named}) -- the target is '
        f'not visible to the API role, so castiron cannot build the relationship. The column is '
        f'emitted as a plain value and no nested model is generated for it; the foreign-key '
        f'constraint is still recorded in the IR.'
    )


def volatility_unknown_functions(schema: Schema) -> list[str]:
    """Return every function name whose volatility the serving PostgREST was too old to encode.

    ⚠ **Source-agnostic, and it needs no new predicate input.** It reads only
    :attr:`~castiron.ir.Schema.postgrest_version`, which is ``None`` for every source that is not
    PostgREST -- so this stays quiet for a DDL or live-DB run without a ``from_openapi`` gate,
    exactly like :func:`dangling_foreign_keys`.

    Args:
        schema: The schema that was just loaded (treated as read-only).

    Returns:
        Every function name, in ``Schema.functions`` order, when the document's PostgREST is below
        the volatility floor; empty otherwise (including when the schema has no functions, which
        makes the fact unactionable).
    """
    if schema.postgrest_version is None or volatility_is_encoded(schema.postgrest_version):
        return []
    return [function.name for function in schema.functions]


def volatility_unknown_warning(names: list[str], postgrest_version: str | None) -> str:
    """Build the unknown-volatility warning for ``names``, naming the version rather than the names.

    ⚠ **Two deliberate deviations from the rest of the family**, both stated here so a reviewer
    reads them as decisions rather than accidents. First, this builder takes a **second argument**:
    the observed version is the actionable half of the message and the remedy depends on it, while
    the names do not distinguish anything. Second, it does **not** use the ``MAX_NAMED_TABLES``
    "and N more" elision, because the affected set is always *every* function -- naming three of
    them would imply the other N-3 were fine.

    Args:
        names: The affected function names (already collected by
            :func:`volatility_unknown_functions`); only their count is reported.
        postgrest_version: The document's verbatim ``info.version``.

    Returns:
        The warning line, in the same voice as :func:`dangling_foreign_key_warning`.
    """
    subject = 'function' if len(names) == 1 else 'functions'
    return (
        f'PostgREST {postgrest_version} does not encode function volatility: below 13.0.5 it serves a GET '
        f'operation for every /rpc/ path, so the document cannot tell a VOLATILE function from a '
        f'STABLE or IMMUTABLE one. castiron reports volatility and is_read_only as unknown for all '
        f'{len(names)} {subject} rather than asserting every one of them is read-only -- a wrong '
        f'read-only is what turns an INSERT into a GET request. Upgrade PostgREST to 13.0.5 or later to '
        f'recover the signal.'
    )


def report(
    schema: Schema,
    *,
    infer_generated_primary_keys: bool,
    from_openapi: bool,
    disable_model_prefix_protection: bool,
    enum_classes: Sequence[EnumClass] = (),
    class_stems: Sequence[ClassStem] = (),
) -> None:
    """Emit the fidelity notices for one ``gen`` run.

    Args:
        schema: The schema that was just loaded.
        infer_generated_primary_keys: Whether the identity inference was enabled. When it
            was, the identity warning is moot and stays quiet.
        from_openapi: Whether the schema came from the OpenAPI source (the only source
            today; the INFO note is specific to its fidelity floor).
        disable_model_prefix_protection: Whether ``model_`` renaming was disabled. Needed to tell
            a ``CI-085`` identifier repair from the shipped reserved-word rename.
        enum_classes: The resolved enum class names, from the emitter that will write them.
            Defaults to empty, so a caller that emits no Python classes reports nothing rather
            than guessing.
        class_stems: The resolved model class stems, from the same emitter and for the same reason.
    """
    if from_openapi:
        logger.info(OPENAPI_FIDELITY_NOTE)
    repaired = repaired_column_names(schema, disable_model_prefix_protection=disable_model_prefix_protection)
    if repaired:
        logger.warning(repaired_column_warning(repaired))
    # Tables before enums, matching the order they are allocated in: a user reading two renames
    # should see the one that displaced the other first.
    renamed_stems = renamed_class_stems(class_stems)
    if renamed_stems:
        logger.warning(renamed_class_stem_warning(renamed_stems))
    renamed = renamed_enum_classes(enum_classes)
    if renamed:
        logger.warning(renamed_enum_class_warning(renamed))
    # ⚠ BEFORE the early return below, and deliberately not gated on `from_openapi`: the condition
    # is a property of the IR, not of the source, and the identity inference has nothing to do with
    # it. Placing it after the return would mute a structural loss for every user of
    # --infer-generated-primary-keys.
    dangling = dangling_foreign_keys(schema)
    if dangling:
        logger.warning(dangling_foreign_key_warning(dangling))
    # Also before the early return, and for the same reason: an old server build has nothing to do
    # with the identity inference, so --infer-generated-primary-keys must not mute it.
    unknown_volatility = volatility_unknown_functions(schema)
    if unknown_volatility:
        logger.warning(volatility_unknown_warning(unknown_volatility, schema.postgrest_version))
    if infer_generated_primary_keys:
        return
    candidates = identity_pk_candidates(schema)
    if candidates:
        logger.warning(identity_pk_warning(candidates))
