"""Fidelity notices — telling the user what the OpenAPI source could not see.

The OpenAPI/PostgREST source needs no database credentials, and pays for it: unique and
check constraints, identity/generated columns, exact integer widths below ``bigint``, and
function return types are simply not encoded in the document (CI-005 spec §11). Two of
those are invisible to the user until their code misbehaves, so this module surfaces the
one that actually bites:

**PostgREST does not expose ``nextval()``/identity defaults.** Every Supabase project's
``id bigint generated by default as identity`` therefore looks like a plain NOT NULL
integer primary key with no default, and castiron marks it *required* on the Insert model.
The fix is one flag (``--infer-generated-primary-keys``), so the warning fires **once**,
and only when it would actually change the output — CI5-D11 rejected per-column
degradation warnings as noise, and this is deliberately not that.
"""

import logging

from castiron.ir import Schema
from castiron.sources.openapi import INTEGER_FAMILY

logger = logging.getLogger(__name__)

#: Raw type tokens the identity inference applies to. Aliased from the source's own
#: constant rather than re-listed, so the CLI notice and the inference cannot drift.
INTEGER_PK_TYPES = INTEGER_FAMILY

#: How many table names the warning spells out before collapsing to "and N more".
MAX_NAMED_TABLES = 3

#: Shown at INFO (``-v``) once per run when the schema came from the OpenAPI source.
OPENAPI_FIDELITY_NOTE = (
    'Read from the OpenAPI source (no database connection): unique/check constraints, identity '
    'columns, exact integer widths below bigint, and function return types are not visible from it.'
)


def identity_pk_candidates(schema: Schema) -> list[str]:
    """Return table names whose sole primary key looks like an un-detected identity column.

    The predicate reads the **IR** — exactly one column with ``primary`` set, NOT NULL, no
    default, not already flagged as identity, and an integer raw type. Known, accepted
    divergence from the source's own inference: the source applies its rule to any
    definition carrying a sole ``<pk/>`` marker, while ``ColumnInfo.primary`` is left
    ``False`` for views (CI5-D14). A view is not a meaningful Insert target, so the warning
    correctly stays quiet for one.

    Args:
        schema: The schema to inspect (treated as read-only).

    Returns:
        The candidate table names, in ``Schema.tables`` order.
    """
    candidates: list[str] = []
    for table in schema.tables:
        primaries = [column for column in table.columns if column.primary]
        if len(primaries) != 1:
            continue
        column = primaries[0]
        if column.nullable() or column.default is not None or column.is_identity:
            continue
        if column.raw_type in INTEGER_PK_TYPES:
            candidates.append(table.name)
    return candidates


def identity_pk_warning(tables: list[str]) -> str:
    """Build the identity-PK warning for ``tables``, naming at most three of them."""
    named = ', '.join(tables[:MAX_NAMED_TABLES])
    if len(tables) > MAX_NAMED_TABLES:
        named = f'{named} and {len(tables) - MAX_NAMED_TABLES} more'
    subject = 'table has' if len(tables) == 1 else 'tables have'
    return (
        f'{len(tables)} {subject} an integer primary key with no visible default ({named}) -- '
        'PostgREST does not expose nextval()/identity defaults, so castiron marks those columns '
        'required on the Insert models. Pass --infer-generated-primary-keys (or set '
        'infer-generated-primary-keys = true) if they are serial/identity columns.'
    )


def report(schema: Schema, *, infer_generated_primary_keys: bool, from_openapi: bool) -> None:
    """Emit the fidelity notices for one ``gen`` run.

    Args:
        schema: The schema that was just loaded.
        infer_generated_primary_keys: Whether the identity inference was enabled. When it
            was, the warning is moot and stays quiet.
        from_openapi: Whether the schema came from the OpenAPI source (the only source
            today; the INFO note is specific to its fidelity floor).
    """
    if from_openapi:
        logger.info(OPENAPI_FIDELITY_NOTE)
    if infer_generated_primary_keys:
        return
    candidates = identity_pk_candidates(schema)
    if candidates:
        logger.warning(identity_pk_warning(candidates))
