"""Shared fixtures for the OpenAPI/PostgREST source tests.

Fixture provenance
------------------
``fixtures/postgrest_openapi.json`` is **hand-authored**, reproducing the literal JSON
shapes asserted by PostgREST's own ``test/spec/Feature/OpenApi/OpenApiSpec.hs`` and
generated by ``src/library/PostgREST/Response/OpenAPI.hs``. It is not a captured document
from a live project: no real project URL, no API key, and nothing here ever opens a socket.
Most shapes in it are attested by the CI-005 spec's §3 (verified 2026-07-31 against the
PostgREST sources listed in ``castiron.sources.openapi.parse``'s module docstring). Do not
invent a new shape here -- if reality disagrees with §3, stop and report it.

⚠ **This fixture is SYNTHETIC, and one of its shapes is fictional. Never cite it as evidence
about what PostgREST emits** (amended 2026-08-02 by CI-007; see WORKPLAN row **CI-076**).

``restricted_table.owner_id`` carries ``<fk table='active_users_view' column='id'/>`` -- **a
VIEW as a foreign-key TARGET**. ``SEED-F1`` measured this against the real apparatus on
PostgREST v14.14 *and* pinned v12.2.3 and **CONFIRMED** that PostgREST never does it: even
when the base table is privilege-filtered and a view over it is visible, the marker names the
invisible *base table*, not the view. SQL cannot express it either -- a Postgres foreign key
can only reference a table.

This paragraph previously read *"Every shape in it is attested by the CI-005 spec's §3"*,
which had become the fixture's own false certificate of authenticity. **The fictional FK
marker's bytes are unchanged deliberately:** correcting them would move
``golden/schema.py.txt``, which three other test modules assert against, and CI-076 owns that
change. What CI-007 does instead is stop the fixture *standing as evidence* -- the corpus
records it as ``provenance='synthetic'``, and ``tests/unit/corpus/test_witnesses.py`` asserts
the fictional marker **is** present, so it is now documented as fiction rather than mistaken
for fact. castiron's evidence about PostgREST comes from the real captures in
``tests/unit/corpus/inputs/``.

What the fixture deliberately exercises:

- ``users`` -- a writable BASE TABLE with an ``int32`` surrogate PK carrying **no default**
  (PostgREST drops ``nextval(...)``), a ``character varying`` + ``maxLength``, a string-ish
  ``now()`` default, a scalar enum with a default, a ``jsonb`` column with **no** ``type``
  key, a ``text[]`` array, a plain-comment description, a Python-keyword column (``class``),
  and numeric/boolean defaults (``0`` / ``false``) that must be stringified, **and a
  table-level SQL comment** (``Application users.``).
- ``orders`` -- an ``int64`` PK, a single-column FK marker preceded by a real SQL comment,
  ``numeric``, ``character`` + ``maxLength: 1``, an **enum array** with no ``enum`` key
  (its labels are unknowable from the document, so it links only via the scalar column),
  and a **table-level SQL comment** (``Customer orders.``).
- ``order_items`` -- a bridge table: a composite PK whose members are both FK columns.
- ``products`` -- the far side of two relationships.
- ``active_users_view`` -- GET-only **and** no ``required`` array => classified ``VIEW``,
  with a **table-level SQL comment** (``Users with a recent login.``) proving a VIEW carries
  one too.
- ``restricted_table`` -- GET-only but **has** ``required`` => stays ``BASE TABLE`` (the
  conservative two-signal heuristic).

``order_items``, ``products`` and ``restricted_table`` deliberately carry **no** table
comment, so the golden proves an uncommented table gains nothing (CI-009).
- ``/rpc/*`` -- ``get_user_stats`` (GET+POST: non-volatile, one defaulted arg),
  ``create_order`` (POST-only: volatile, an enum arg and an array arg), ``ping``
  (POST-only, zero args), and ``search_products`` (GET+POST with a VARIADIC arg visible
  only through the GET operation's ``collectionFormat: multi``).

Every ``/rpc/*`` POST body's ``properties`` object is **alphabetical by argument name**, which
is what PostgREST emits (measured in ``test_parse.py``'s
``TestRpcParameterOrderInTheRealCaptures``, swept over both committed captures). Until
``CI-133`` these were in *declaration* order -- a document shape the generator cannot produce
-- so the parameter-order tests reading them agreed with a fiction. Keep new RPC bodies
sorted. The GET operations keep declaration order, because that is what PostgREST does there,
and that asymmetry is the point: it is the only place declaration order survives (``CI-078``).

**Overloads are not representable.** PostgREST maps every overload of ``f`` to the single
path key ``/rpc/f`` and the last one wins, so the fixture cannot contain two signatures for
one name; ``test_parse.py`` asserts exactly one function per ``/rpc/*`` key instead.

⚠ **``info.version`` was ``'12.2.3 (abcdef0)'`` until ``CI-145``, and that was a third instance
of the CI-076 class: a document a real PostgREST could not have produced.** The fixture's
``/rpc/`` verb sets are **mixed** -- ``('get', 'post')`` on ``get_user_stats`` and
``search_products``, ``('post',)`` on ``create_order`` and ``ping``. A real 12.2.3 emits ``get``
on **all four**: ``makeProcPathItem`` only learned to withhold it for VOLATILE functions in
**13.0.5** (PR #4174, CHANGELOG ``[13.0.5] - 2025-08-24``), and the ``v12.2.3``, ``v12.2.12`` and
``v13.0.4`` sources are unconditional. The verb shape is the >= 13.0.5 shape, so the *version*
is what was wrong and it is now ``'14.14'``. Repaired in the same direction as ``CI-133``, which
corrected this same fixture's RPC body ordering for exactly this reason. Do **not** "fix" it the
other way by adding GETs to the two POST-only paths: that would make it a sub-floor document and
destroy the above-floor coverage four test modules depend on.

``fixtures/postgrest_openapi_v12_shaped.json`` is the **sub-floor** counterpart, added by
``CI-141``. It is deliberately tiny (one table, three ``/rpc/`` paths) and **SYNTHETIC** -- see
its own ``info.description``, which carries the full label and the upstream citations. It is
evidence about **castiron**, never about PostgREST: the claim it embodies (a PostgREST < 13.0.5
serves a ``get`` for every ``/rpc/`` path) rests on the generator source, not on this file.
"""

import json
from pathlib import Path
from typing import Any

import pytest

FIXTURE_DIR = Path(__file__).parent / 'fixtures'
GOLDEN_DIR = Path(__file__).parent / 'golden'


def load_fixture(name: str) -> dict[str, Any]:
    """Load a JSON fixture document by file name."""
    document: dict[str, Any] = json.loads((FIXTURE_DIR / name).read_text(encoding='utf-8'))
    return document


@pytest.fixture
def document() -> dict[str, Any]:
    """The representative PostgREST OpenAPI document."""
    return load_fixture('postgrest_openapi.json')


@pytest.fixture
def sub_floor_document() -> dict[str, Any]:
    """A SYNTHETIC document shaped the way a PostgREST below 13.0.5 serves one (``CI-141``).

    ``info.version`` is ``'12.2.3 (519615d)'`` and **every** ``/rpc/`` path carries a ``get``,
    including ``probe_volatile_bump``, which is a mutation. Hand-authored: it proves what castiron
    does given a version string and a document shape, and nothing whatsoever about PostgREST.
    """
    return load_fixture('postgrest_openapi_v12_shaped.json')


@pytest.fixture
def openapi3_document() -> dict[str, Any]:
    """An OpenAPI 3 document -- castiron must refuse it, loudly."""
    return load_fixture('openapi3_document.json')


@pytest.fixture
def empty_definitions_document() -> dict[str, Any]:
    """A valid Swagger 2.0 document whose ``definitions`` are empty (RLS/privileges)."""
    return load_fixture('empty_definitions.json')
