"""Shared fixtures for the OpenAPI/PostgREST source tests.

Fixture provenance
------------------
``fixtures/postgrest_openapi.json`` is **hand-authored**, reproducing the literal JSON
shapes asserted by PostgREST's own ``test/spec/Feature/OpenApi/OpenApiSpec.hs`` and
generated by ``src/library/PostgREST/Response/OpenAPI.hs``. It is not a captured document
from a live project: no real project URL, no API key, and nothing here ever opens a socket.
Every shape in it is attested by the CI-005 spec's §3 (verified 2026-07-31 against the
PostgREST sources listed in ``castiron.sources.openapi.parse``'s module docstring). Do not
invent a new shape here -- if reality disagrees with §3, stop and report it.

What the fixture deliberately exercises:

- ``users`` -- a writable BASE TABLE with an ``int32`` surrogate PK carrying **no default**
  (PostgREST drops ``nextval(...)``), a ``character varying`` + ``maxLength``, a string-ish
  ``now()`` default, a scalar enum with a default, a ``jsonb`` column with **no** ``type``
  key, a ``text[]`` array, a plain-comment description, a Python-keyword column (``class``),
  and numeric/boolean defaults (``0`` / ``false``) that must be stringified, **and a
  table-level SQL comment** (``Application users.``).
- ``orders`` -- an ``int64`` PK, a single-column FK marker preceded by a real SQL comment,
  ``numeric``, ``character`` + ``maxLength: 1``, an **enum array** with no ``enum`` key
  (its labels are unknowable from the document, so it links only via the scalar column),
  and a **table-level SQL comment** (``Customer orders.``).
- ``order_items`` -- a bridge table: a composite PK whose members are both FK columns.
- ``products`` -- the far side of two relationships.
- ``active_users_view`` -- GET-only **and** no ``required`` array => classified ``VIEW``,
  with a **table-level SQL comment** (``Users with a recent login.``) proving a VIEW carries
  one too.
- ``restricted_table`` -- GET-only but **has** ``required`` => stays ``BASE TABLE`` (the
  conservative two-signal heuristic).

``order_items``, ``products`` and ``restricted_table`` deliberately carry **no** table
comment, so the golden proves an uncommented table gains nothing (CI-009).
- ``/rpc/*`` -- ``get_user_stats`` (GET+POST: non-volatile, one defaulted arg),
  ``create_order`` (POST-only: volatile, an enum arg and an array arg), ``ping``
  (POST-only, zero args), and ``search_products`` (GET+POST with a VARIADIC arg visible
  only through the GET operation's ``collectionFormat: multi``).

**Overloads are not representable.** PostgREST maps every overload of ``f`` to the single
path key ``/rpc/f`` and the last one wins, so the fixture cannot contain two signatures for
one name; ``test_parse.py`` asserts exactly one function per ``/rpc/*`` key instead.
"""

import json
from pathlib import Path
from typing import Any

import pytest

FIXTURE_DIR = Path(__file__).parent / 'fixtures'
GOLDEN_DIR = Path(__file__).parent / 'golden'


def load_fixture(name: str) -> dict[str, Any]:
    """Load a JSON fixture document by file name."""
    document: dict[str, Any] = json.loads((FIXTURE_DIR / name).read_text(encoding='utf-8'))
    return document


@pytest.fixture
def document() -> dict[str, Any]:
    """The representative PostgREST OpenAPI document."""
    return load_fixture('postgrest_openapi.json')


@pytest.fixture
def openapi3_document() -> dict[str, Any]:
    """An OpenAPI 3 document -- castiron must refuse it, loudly."""
    return load_fixture('openapi3_document.json')


@pytest.fixture
def empty_definitions_document() -> dict[str, Any]:
    """A valid Swagger 2.0 document whose ``definitions`` are empty (RLS/privileges)."""
    return load_fixture('empty_definitions.json')
